#BECOFARMA_LAPTOP
SERVIDOR_BD_WMS = DELL
NOMBRE_BD_WMS = IMS4MB_BECOFARMA_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =192.168.0.129:40000
SERVER_BD_SAP = sqlsrv
SAP_COMPANY_DB = TEST_BACH_19012024
SAP_USR = manager
SAP_USR_PW = 2023CC
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
TIMEOUT = 0
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
#FIN

#BECOFARMA_PRD
SERVIDOR_BD_WMS = 10.238.113.198
NOMBRE_BD_WMS = IMS4MB_BECOFARMA_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =10.238.113.195:40000
SERVER_BD_SAP = 10.238.113.194
SAP_COMPANY_DB = DB_Becofarma_2016
SAP_USR = sap_wms
SAP_USR_PW = 1234
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
SAP_DB_VERSION = 2019
TIMEOUT = 0
IDCONFIGURACION = 1
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
#FIN

#BECOFARMA_QAS
SERVIDOR_BD_WMS = 10.238.113.198
NOMBRE_BD_WMS = IMS4MB_BECOFARMA_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =10.238.113.195:40000
SERVER_BD_SAP = 10.238.113.194
SAP_COMPANY_DB = TEST_BACH_19012024
SAP_USR = sap_wms
SAP_USR_PW = 1234
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
SAP_DB_VERSION = 2019
TIMEOUT = 0
IDCONFIGURACION = 1
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
#FIN

#CLARISFARMA_QA
SERVIDOR_BD_WMS = 10.238.113.198
NOMBRE_BD_WMS = IMS4MB_CLARISFARMA_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =10.238.113.195:40000
SERVER_BD_SAP = 10.238.113.194
SAP_COMPANY_DB = TEST_SBO_CLARIS_14062024
SAP_USR = manager
SAP_USR_PW = Cl@ris2024
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
SAP_DB_VERSION = 2019
TIMEOUT = 0
IDCONFIGURACION = 1
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
#FIN

#CLARISFARMA_PRD
SERVIDOR_BD_WMS = 10.238.113.198
NOMBRE_BD_WMS = IMS4MB_CLARISPHARMA_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =10.238.113.195:40000
SERVER_BD_SAP = 10.238.113.194
SAP_COMPANY_DB = SBO_CLARIS
SAP_USR = sap_wms
SAP_USR_PW = 1234
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
SAP_DB_VERSION = 2019
TIMEOUT = 0
IDCONFIGURACION = 1
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
#FIN