Imports System.Reflection
Imports DevExpress.XtraEditors

Public Class frmEstSector

    Sub New()
        InitializeComponent()
    End Sub

    Public IdSector As Integer = 0
    Public Property IdBodega As Integer = 0

    Private listBeEstructuraTramos As New List(Of clsBeEstructura_tramo)
    Private BeEstructura_tramo As New clsBeEstructura_tramo
    Private BeSector As New clsBeBodega_sector


#Region " Metodos principales "

    Private Sub frmEstSector_Load(sender As Object, e As EventArgs) Handles MyBase.Load

        Try

            Carga_Registros()

            Actualizar_Grid()

        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

    End Sub

    Private Sub Actualizar_Grid()

        Try

            ' This line of code is generated by Data Source Configuration Wizard
            Bodega_sectorTableAdapter1.Fill(DetTramoByBodega1.bodega_sector, IdBodega)


        Catch ex As Exception
            XtraMessageBox.Show(String.Format("{0} {1}", MethodBase.GetCurrentMethod.Name(), ex.Message),
    Text,
    MessageBoxButtons.OK,
    MessageBoxIcon.Error)
        End Try

    End Sub

    Private Sub Carga_Registros()

        grdIzq.Rows.Clear()
        grdDer.Rows.Clear()

        Try

            listBeEstructuraTramos = clsLnEstructura_tramo.Get_All_By_IdSector(IdSector, AP.IdBodega)

            For Each t As clsBeEstructura_tramo In listBeEstructuraTramos

                If t.Horizontal Then
                    If t.Orientacion = 1 Then
                        grdIzq.Rows.Add(t.IdTramo,
                                        t.Descripcion,
                                        t.Largo,
                                        t.Ancho,
                                        t.Margen_izquierdo,
                                        t.Margen_superior,
                                        t.Sistema,
                                        t.Horizontal,
                                        t.Orden_Descendente)

                    Else
                        grdDer.Rows.Add(t.IdTramo,
                                        t.Descripcion,
                                        t.Largo,
                                        t.Ancho,
                                        t.Margen_izquierdo,
                                        t.Margen_superior,
                                        t.Sistema,
                                        t.Horizontal,
                                        t.Orden_Descendente)
                    End If
                Else
                    If t.Orientacion = 0 Then
                        grdIzq.Rows.Add(t.IdTramo,
                                        t.Descripcion,
                                        t.Largo,
                                        t.Ancho,
                                        t.Margen_izquierdo,
                                        t.Margen_superior,
                                        t.Sistema,
                                        t.Horizontal,
                                        t.Orden_Descendente)
                    Else
                        grdDer.Rows.Add(t.IdTramo,
                                        t.Descripcion,
                                        t.Largo,
                                        t.Ancho,
                                        t.Margen_izquierdo,
                                        t.Margen_superior,
                                        t.Sistema,
                                        t.Horizontal,
                                        t.Orden_Descendente)
                    End If
                End If

            Next

        Catch ex As Exception
            XtraMessageBox.Show(String.Format("{0} {1}", MethodBase.GetCurrentMethod.Name(), ex.Message),
                        Text,
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Error)
        End Try

    End Sub

    Private Function Guardar_Tramos() As Boolean

        Dim vEliminarTramo As Boolean = False

        Try

            If XtraMessageBox.Show("Se sugiere eliminar el detalle si modificó (márgenes, tamaño, etc), ¿Eliminar detalle?", Text,
                        MessageBoxButtons.YesNo,
                        MessageBoxIcon.Error) = vbYes Then
                vEliminarTramo = True
            End If

            Return clsLnEstructura_Tramo.Procesa_Batch(IdSector, listBeEstructuraTramos, vEliminarTramo)

        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

    End Function

    Private Function Datos_Validos() As Boolean

        Dim IdTramo, MaxId As Integer
        Dim Codigo, Nombre As String
        Dim largo, ancho, m_izq, m_sup As Double


        listBeEstructuraTramos.Clear()

        grdIzq.EndEdit() : grdDer.EndEdit()

        MaxId = clsLnEstructura_tramo.MaxID()

        For vI = 0 To grdIzq.Rows.Count - 2

            Try

                Codigo = grdIzq.Rows(vI).Cells(0).Value

                Try
                    IdTramo = Codigo
                    If (IdTramo = 0) Then Throw New Exception
                Catch ex As Exception
                    MaxId += 1 : IdTramo = MaxId
                End Try

                Nombre = grdIzq.Rows(vI).Cells(1).Value : If Nombre = "" Then Throw New Exception

                largo = grdIzq.Rows(vI).Cells(2).Value : If largo < 0 Then Throw New Exception
                ancho = grdIzq.Rows(vI).Cells(3).Value : If ancho < 0 Then Throw New Exception
                m_izq = grdIzq.Rows(vI).Cells(4).Value : If m_izq < 0 Then Throw New Exception
                m_sup = grdIzq.Rows(vI).Cells(5).Value : If m_sup < 0 Then Throw New Exception

                BeEstructura_tramo = clsLnEstructura_tramo.Crear_Default(AP.UsuarioAp.IdUsuario)

                BeEstructura_tramo.IdArea = BeSector.IdArea
                BeEstructura_tramo.IdSector = IdSector
                BeEstructura_tramo.IdTramo = IdTramo
                BeEstructura_tramo.Descripcion = Nombre

                BeEstructura_tramo.Largo = largo
                BeEstructura_tramo.Ancho = ancho
                BeEstructura_tramo.Margen_izquierdo = m_izq
                BeEstructura_tramo.Margen_superior = m_sup

                BeEstructura_tramo.Codigo = IdTramo
                BeEstructura_tramo.Indice_x = vI + 1
                BeEstructura_tramo.IdBodega = AP.IdBodega
                BeEstructura_tramo.Sistema = grdIzq.Rows(vI).Cells(6).Value
                BeEstructura_tramo.Horizontal = grdIzq.Rows(vI).Cells(7).Value
                BeEstructura_tramo.Orden_Descendente = grdIzq.Rows(vI).Cells(8).Value

                BeEstructura_tramo.Orientacion = IIf(BeEstructura_tramo.Horizontal, 1, 0)

                listBeEstructuraTramos.Add(BeEstructura_tramo)

            Catch ex As Exception

                grdIzq.Focus()
                grdIzq.ClearSelection()
                grdIzq.Rows(vI).Selected = True
                grdIzq.FirstDisplayedScrollingRowIndex = vI

                MsgBox("Panel izquierdo , linea " & vI + 1 & " : datos incorrectos")

                Return False

            End Try
        Next

        For vI = 0 To grdDer.Rows.Count - 2
            Try

                Codigo = grdDer.Rows(vI).Cells(0).Value

                Try
                    IdTramo = Codigo
                    If (IdTramo = 0) Then Throw New Exception
                Catch ex As Exception
                    MaxId += 1 : IdTramo = MaxId
                End Try

                Nombre = grdDer.Rows(vI).Cells(1).Value : If Nombre = "" Then Throw New Exception

                largo = grdDer.Rows(vI).Cells(2).Value : If largo < 0 Then Throw New Exception
                ancho = grdDer.Rows(vI).Cells(3).Value : If ancho < 0 Then Throw New Exception
                m_izq = grdDer.Rows(vI).Cells(4).Value : If m_izq < 0 Then Throw New Exception
                m_sup = grdDer.Rows(vI).Cells(5).Value : If m_sup < 0 Then Throw New Exception

                BeEstructura_tramo = clsLnEstructura_tramo.Crear_Default(AP.UsuarioAp.IdUsuario)

                BeEstructura_tramo.IdArea = BeSector.IdArea
                BeEstructura_tramo.IdSector = IdSector
                BeEstructura_tramo.IdTramo = IdTramo
                BeEstructura_tramo.Descripcion = Nombre

                BeEstructura_tramo.Largo = largo
                BeEstructura_tramo.Ancho = ancho
                BeEstructura_tramo.Margen_izquierdo = m_izq
                BeEstructura_tramo.Margen_superior = m_sup

                BeEstructura_tramo.Codigo = IdTramo
                BeEstructura_tramo.Indice_x = vI + 1
                BeEstructura_tramo.IdBodega = AP.IdBodega
                BeEstructura_tramo.Sistema = grdDer.Rows(vI).Cells(6).Value
                BeEstructura_tramo.Horizontal = grdDer.Rows(vI).Cells(7).Value
                BeEstructura_tramo.Orden_Descendente = grdDer.Rows(vI).Cells(8).Value

                BeEstructura_tramo.Orientacion = IIf(BeEstructura_tramo.Horizontal, 0, 1)

                listBeEstructuraTramos.Add(BeEstructura_tramo)

            Catch ex As Exception

                grdDer.Focus()
                grdDer.ClearSelection()
                grdDer.Rows(vI).Selected = True
                grdDer.FirstDisplayedScrollingRowIndex = vI

                MsgBox("Panel derecho , linea " & vI + 1 & " : datos incorrectos")

                Return False

            End Try
        Next

        Return True

    End Function

#End Region

#Region " Eventos "

    Private Sub mnuActualizar_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuActualizar.ItemClick

        mnuActualizar.Enabled = False
        If Datos_Validos() Then
            If Guardar_Tramos() Then
                XtraMessageBox.Show("Datos guardados correctamente", Text, MessageBoxButtons.OK, MessageBoxIcon.Information)
                Close()
            End If
        End If
        mnuActualizar.Enabled = True
    End Sub

    Private Sub grdIzq_KeyDown(sender As Object, e As KeyEventArgs) Handles grdIzq.KeyDown

        Dim ri As Integer

        If e.KeyCode = Keys.V And e.Control Then
            Paste_Izq() : Return
        End If

        If e.KeyCode = Keys.Insert Then
            Try
                ri = grdIzq.CurrentRow.Index
                grdIzq.Rows.Insert(ri)
            Catch ex As Exception
                grdIzq.Rows.Add()
            End Try
            Return
        End If

        If e.KeyCode = Keys.Delete Then
            Try
                ri = grdIzq.CurrentRow.Index
                grdIzq.Rows.RemoveAt(ri)
            Catch ex As Exception
            End Try
            Return
        End If

    End Sub

    Private Sub grdDer_KeyDown(sender As Object, e As KeyEventArgs) Handles grdDer.KeyDown

        Dim ri As Integer

        If e.KeyCode = Keys.V And e.Control Then
            Paste_Der() : Return
        End If

        If e.KeyCode = Keys.Insert Then
            Try
                ri = grdDer.CurrentRow.Index
                grdDer.Rows.Insert(ri)
            Catch ex As Exception
                grdDer.Rows.Add()
            End Try
            Return
        End If

        If e.KeyCode = Keys.Delete Then
            Try
                ri = grdDer.CurrentRow.Index
                grdDer.Rows.RemoveAt(ri)
            Catch ex As Exception
            End Try
            Return
        End If

    End Sub

    Private Sub btnPegarIzq_Click(sender As Object, e As EventArgs) Handles btnPegarIzq.Click
        Paste_Izq()
    End Sub

    Private Sub btnInsIzq_Click(sender As Object, e As EventArgs) Handles btnInsIzq.Click

        Dim ri As Integer

        Try

            If Not grdIzq.CurrentRow Is Nothing Then
                ri = grdIzq.CurrentRow.Index
                grdIzq.Rows.Insert(ri)
            Else
                XtraMessageBox.Show("Error: valide datos",
                                        Text,
                                        MessageBoxButtons.OK,
                                        MessageBoxIcon.Error)
            End If

        Catch ex As Exception
            grdIzq.Rows.Add()
        End Try

    End Sub

    Private Sub btnBorIzq_Click(sender As Object, e As EventArgs) Handles btnBorIzq.Click

        Dim ri As Integer

        Try

            If AP.IdBodega = AP.IdBodegaAnterior Then

                ri = grdIzq.CurrentRow.Index
                grdIzq.Rows.RemoveAt(ri)

            Else

                If XtraMessageBox.Show(String.Format("¿Está seguro de borrar el tramo {0}?", grdIzq.CurrentRow.Cells(1).Value), Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then

                    If XtraMessageBox.Show("¿Está totalmente seguro?", Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then

                        ri = grdIzq.CurrentRow.Index
                        grdIzq.Rows.RemoveAt(ri)

                    End If

                End If

            End If


        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
        End Try

    End Sub

    Private Sub btnLimpiarIzq_Click(sender As Object, e As EventArgs) Handles btnLimpiarIzq.Click

        If AP.IdBodega = AP.IdBodegaAnterior Then

            If MessageBox.Show("Borrar todos los registros", "", MessageBoxButtons.YesNo) = DialogResult.Yes Then grdIzq.Rows.Clear()

        Else

            If XtraMessageBox.Show("¿Está seguro de borrar todos los tramos?", Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then

                If XtraMessageBox.Show("¿Está totalmente seguro?", Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then

                    grdIzq.Rows.Clear()

                End If

            End If

        End If

    End Sub

    Private Sub btnPegarDer_Click(sender As Object, e As EventArgs) Handles btnPegarDer.Click
        Paste_Der()
    End Sub

    Private Sub btnInsDer_Click(sender As Object, e As EventArgs) Handles btnInsDer.Click

        Dim ri As Integer

        Try
            ri = grdDer.CurrentRow.Index
            grdDer.Rows.Insert(ri)
        Catch ex As Exception
            grdDer.Rows.Add()
        End Try

    End Sub

    Private Sub btnBorDer_Click(sender As Object, e As EventArgs) Handles btnBorDer.Click

        Dim ri As Integer

        Try


            If AP.IdBodega = AP.IdBodegaAnterior Then

                ri = grdDer.CurrentRow.Index
                grdDer.Rows.RemoveAt(ri)

            Else

                If XtraMessageBox.Show(String.Format("¿Está seguro de borrar el tramo {0}?", grdDer.CurrentRow.Cells(0).Value), Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then

                    If XtraMessageBox.Show("¿Está totalmente seguro?", Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then

                        ri = grdDer.CurrentRow.Index
                        grdDer.Rows.RemoveAt(ri)

                    End If

                End If

            End If
        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
        End Try

    End Sub

    Private Sub btnLimpiarDer_Click(sender As Object, e As EventArgs) Handles btnLimpiarDer.Click


        If AP.IdBodega = AP.IdBodegaAnterior Then

            If MessageBox.Show("Borrar todos los registros", "", MessageBoxButtons.YesNo) = DialogResult.Yes Then grdDer.Rows.Clear()

        Else

            If XtraMessageBox.Show(String.Format("¿Está seguro de borrar el tramo {0}?", grdDer.CurrentRow.Cells(0).Value), Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then

                If XtraMessageBox.Show("¿Está totalmente seguro?", Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then

                    grdDer.Rows.Clear()

                End If

            End If

        End If

    End Sub

    Private Sub grdIzq_CellEndEdit(sender As Object, e As DataGridViewCellEventArgs) Handles grdIzq.CellEndEdit

        Dim os, ns As String

        If e.ColumnIndex <> 1 Then Return

        Try
            os = grdIzq.Rows(e.RowIndex).Cells(1).Value : os = UCase(os)
            ns = Parse_String(os)
            grdIzq.Rows(e.RowIndex).Cells(1).Value = ns
            If os <> ns Then MsgBox("Nombre ajustado al formato requerido.")
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

    End Sub

    Private Sub grdDer_CellEndEdit(sender As Object, e As DataGridViewCellEventArgs) Handles grdDer.CellEndEdit

        Dim os, ns As String

        If e.ColumnIndex <> 1 Then Return

        Try

            os = grdDer.Rows(e.RowIndex).Cells(1).Value : os = UCase(os)
            ns = Parse_String(os)
            grdDer.Rows(e.RowIndex).Cells(1).Value = ns

            If os <> ns Then MsgBox("Nombre ajustado al formato requerido.")

        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

    End Sub

#End Region

#Region " Aux "

    Private Sub Paste_Izq()

        Dim vArr() As String
        Dim vRow() As String
        Dim vI, vII, vCC, vR, vRL, vRows As Integer

        grdIzq.SuspendLayout()

        Try

            vArr = Clipboard.GetText().Split(Environment.NewLine)

            vR = grdIzq.Rows.Count

            vRows = vArr.Length
            vRow = vArr(0).Split(vbTab)
            grdIzq.Rows.Add(vRows)

            For vI = 0 To vArr.Length - 1

                If vArr(vI) <> "" Then

                    vRow = vArr(vI).Split(vbTab) : vCC = 0
                    vRL = vRow.Length : If vRL > 5 Then vRL = 5

                    grdIzq.Item(vCC, 0).Value = ""

                    For vII = 0 To vRL - 1
                        grdIzq.Item(vCC + 1, vR).Value = vRow(vII).TrimStart
                        vCC = vCC + 1
                    Next

                    vR = vR + 1

                End If

            Next

        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
        End Try

        For vI = grdIzq.Rows.Count - 1 To 0 Step -1
            Try
                If grdIzq.Rows(vI).Cells(1).Value = "" Then grdIzq.Rows.RemoveAt(vI)
            Catch ex As Exception
            End Try
        Next

        grdIzq.ResumeLayout()

    End Sub

    Private Sub Paste_Der()

        Dim vArr() As String
        Dim vRow() As String
        Dim vI, vII, vCC, vR, vRL, vRows As Integer

        grdDer.SuspendLayout()

        Try

            vArr = Clipboard.GetText().Split(Environment.NewLine)
            vR = grdDer.Rows.Count

            vRows = vArr.Length
            vRow = vArr(0).Split(vbTab)
            grdDer.Rows.Add(vRows)

            For vI = 0 To vArr.Length - 1

                If vArr(vI) <> "" Then

                    vRow = vArr(vI).Split(vbTab) : vCC = 0
                    vRL = vRow.Length : If vRL > 5 Then vRL = 5

                    grdDer.Item(vCC, 0).Value = ""

                    For vII = 0 To vRow.Length - 1
                        grdDer.Item(vCC + 1, vR).Value = vRow(vII).TrimStart
                        vCC = vCC + 1
                    Next

                    vR = vR + 1

                End If

            Next

        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
        End Try

        For vI = grdDer.Rows.Count - 1 To 0 Step -1
            Try
                If grdDer.Rows(vI).Cells(1).Value = "" Then grdDer.Rows.RemoveAt(vI)
            Catch ex As Exception
            End Try
        Next

        grdDer.ResumeLayout()

    End Sub

    Private Function Parse_String(ByVal ss As String) As String

        Dim s1, s2 As String
        Dim sp() As String

        Try

            sp = ss.Split("-")
            s1 = sp(0) : s1 = Mid(s1, 1, 3)
            s2 = sp(1) : s2 = Mid(s2, 1, 2)

        Catch ex As Exception
            s1 = Mid(ss, 1, 3) : s2 = ""
        End Try

        Return UCase(s1 & "-" & s2)

    End Function

    Private Sub frmEstSector_Shown(sender As Object, e As EventArgs) Handles Me.Shown

        Try

            BeSector = clsLnBodega_sector.GetSingle(IdSector, AP.IdBodega)

        Catch ex As Exception
            MsgBox(ex.Message)
        End Try

    End Sub

    Private Sub mnuRevisarEstructura_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs)

        Try

            clsLnBodega_sector.GetAll()

        Catch ex As Exception

        End Try

    End Sub

    Private Sub mnuGuardarDatosGrid_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuGuardarDatosGrid.ItemClick

        Try

            If gvTramo.UpdateCurrentRow() Then

                Bodega_sectorTableAdapter1.Update(DetTramoByBodega1.bodega_sector)

                XtraMessageBox.Show("Registro actualizado",
                    Text,
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information)

                Actualizar_Grid()

            End If


        Catch ex As Exception
            XtraMessageBox.Show(String.Format("{0} {1}", MethodBase.GetCurrentMethod.Name(), ex.Message),
                        Text,
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Error)
        End Try


    End Sub


#End Region

End Class