'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SiteContent
    Public Property SiteContentID As System.Guid
    Public Property FileName As String
    Public Property Path As String
    Public Property ContentType As String
    Public Property Length As Nullable(Of Integer)
    Public Property Data As Byte()
    Public Property Text As String
    Public Property Roles As String
    Public Property RoleExceptions As String
    Public Property Users As String
    Public Property UserExceptions As String
    Public Property Schedule As String
    Public Property ScheduleExceptions As String
    Public Property CacheProfile As String
    Public Property CreatedDate As Nullable(Of Date)
    Public Property ModifiedDate As Nullable(Of Date)

End Class
