'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_empresa_registro
    Public Property IdRegistroAWS As Integer
    Public Property NombreEmpresa As String
    Public Property AWSToken As String
    Public Property IdVersionBD As Nullable(Of Integer)
    Public Property Fecha_Version As Nullable(Of Date)
    Public Property Fecha_Actualizacion As Nullable(Of Date)
    Public Property URL_WS_HH_QA As String
    Public Property URL_WS_HH_PRD As String

    Public Overridable Property tbl_version_bd_wms As tbl_version_bd_wms

End Class
