param(
    [string]$BrainRoot = "C:/Users/yejc2/source/repos/wms-brain/wms-brain",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"

function Get-RelativePath([string]$BasePath, [string]$FullPath) {
    $base = [System.IO.Path]::GetFullPath($BasePath).TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar
    $full = [System.IO.Path]::GetFullPath($FullPath)
    return $full.Substring($base.Length).Replace('\', '/')
}

function Get-FirstMatchingLine([string[]]$Lines, [string]$Pattern) {
    foreach ($line in $Lines) {
        if ($line -match $Pattern) {
            return $line.Trim()
        }
    }
    return ""
}

function Get-YamlValue([string[]]$Lines, [string[]]$Keys) {
    foreach ($key in $Keys) {
        foreach ($line in $Lines) {
            if ($line -match "^\s*$key\s*:\s*(.+)$") {
                return (($line -replace "^\s*$key\s*:\s*", "").Trim().Trim('"').Trim("'"))
            }
        }
    }
    return ""
}

function Get-DocSummary([string]$Path) {
    $lines = Get-Content -LiteralPath $Path -TotalCount 80
    $title = Get-YamlValue $lines @("name", "nombre", "title", "titulo", "slug", "id")

    if (-not $title -and ($Path.EndsWith(".yml") -or $Path.EndsWith(".yaml"))) {
        $metaTitle = Get-YamlValue $lines @("modulo", "objetivo")
        if ($metaTitle) {
            $title = $metaTitle
        }
    }

    if (-not $title) {
        $title = Get-FirstMatchingLine $lines '^\s*#\s+(.+)'
    }

    if ($title) {
        $title = ($title -replace '^\s*#\s+', '').Trim()
    }

    $description = Get-YamlValue $lines @("description", "descripcion", "proposito", "objetivo")

    if (-not $title) {
        $title = [System.IO.Path]::GetFileNameWithoutExtension($Path)
    }

    return @{
        title = $title
        description = $description
    }
}

function Add-Entry([System.Collections.Generic.List[object]]$Entries, [string]$Type, [string]$Path, [string]$BrainRoot) {
    $summary = Get-DocSummary $Path
    $Entries.Add([pscustomobject]@{
        type = $Type
        path = Get-RelativePath $BrainRoot $Path
        title = $summary.title
        description = $summary.description
    }) | Out-Null
}

$brainDir = Join-Path $BrainRoot "brain"
if (-not (Test-Path $brainDir)) {
    throw "Brain directory not found: $brainDir"
}

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $brainDir "_index/AGENT-ROUTING-INDEX.yml"
}

$entries = [System.Collections.Generic.List[object]]::new()

$scanSets = @(
    @{ type = "agent-domain"; path = "agents"; filter = "domain-*.yml" },
    @{ type = "agent-core"; path = "agents"; filter = "_index.yml" },
    @{ type = "agent-core"; path = "agents"; filter = "coordinator.yml" },
    @{ type = "operational-trace"; path = "handoffs"; filter = "*.yml" },
    @{ type = "code-pattern"; path = "code-changes"; filter = "PATTERNS-*.md" },
    @{ type = "skill"; path = "skills"; filter = "SKILL.md" },
    @{ type = "skill-reference"; path = "skills"; filter = "*.md" }
)

foreach ($set in $scanSets) {
    $root = Join-Path $brainDir $set.path
    if (-not (Test-Path $root)) {
        continue
    }

    $files = Get-ChildItem -LiteralPath $root -Recurse -File -Filter $set.filter -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -notmatch '\\\.git\\|\\bin\\|\\obj\\|__pycache__' }

    foreach ($file in $files) {
        Add-Entry -Entries $entries -Type $set.type -Path $file.FullName -BrainRoot $BrainRoot
    }
}

$now = Get-Date -Format "yyyy-MM-ddTHH:mm:ssK"
$linesOut = [System.Collections.Generic.List[string]]::new()
$linesOut.Add("# Generated by wms-build-routing-index.ps1. Safe to regenerate.") | Out-Null
$linesOut.Add("generated_at: ""$now""") | Out-Null
$linesOut.Add("entry_count: $($entries.Count)") | Out-Null
$linesOut.Add("entries:") | Out-Null

foreach ($entry in ($entries | Sort-Object type, path)) {
    $title = ($entry.title -replace '"', '\"')
    $description = ($entry.description -replace '"', '\"')
    $linesOut.Add("  - type: ""$($entry.type)""") | Out-Null
    $linesOut.Add("    path: ""$($entry.path)""") | Out-Null
    $linesOut.Add("    title: ""$title""") | Out-Null
    if ($description) {
        $linesOut.Add("    description: ""$description""") | Out-Null
    }
}

$outputDir = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
Set-Content -LiteralPath $OutputPath -Value $linesOut -Encoding UTF8

Write-Output "Generated routing index: $OutputPath"
Write-Output "Entries: $($entries.Count)"
