'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WCFPropietarioReglaRecepcion
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="clsBePropietario_reglas_enc", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class clsBePropietario_reglas_enc
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fec_agrField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fec_modField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdMensajeReglaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdPropietarioField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdReglaPropietarioEncField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdReglaRecepcionField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsNewField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PropietarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReglaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReglasDetField() As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private User_agrField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private User_modField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fec_agr() As Date
            Get
                Return Me.Fec_agrField
            End Get
            Set
                If (Me.Fec_agrField.Equals(value) <> true) Then
                    Me.Fec_agrField = value
                    Me.RaisePropertyChanged("Fec_agr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fec_mod() As Date
            Get
                Return Me.Fec_modField
            End Get
            Set
                If (Me.Fec_modField.Equals(value) <> true) Then
                    Me.Fec_modField = value
                    Me.RaisePropertyChanged("Fec_mod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdMensajeRegla() As Integer
            Get
                Return Me.IdMensajeReglaField
            End Get
            Set
                If (Me.IdMensajeReglaField.Equals(value) <> true) Then
                    Me.IdMensajeReglaField = value
                    Me.RaisePropertyChanged("IdMensajeRegla")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdPropietario() As Integer
            Get
                Return Me.IdPropietarioField
            End Get
            Set
                If (Me.IdPropietarioField.Equals(value) <> true) Then
                    Me.IdPropietarioField = value
                    Me.RaisePropertyChanged("IdPropietario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdReglaPropietarioEnc() As Integer
            Get
                Return Me.IdReglaPropietarioEncField
            End Get
            Set
                If (Me.IdReglaPropietarioEncField.Equals(value) <> true) Then
                    Me.IdReglaPropietarioEncField = value
                    Me.RaisePropertyChanged("IdReglaPropietarioEnc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdReglaRecepcion() As Integer
            Get
                Return Me.IdReglaRecepcionField
            End Get
            Set
                If (Me.IdReglaRecepcionField.Equals(value) <> true) Then
                    Me.IdReglaRecepcionField = value
                    Me.RaisePropertyChanged("IdReglaRecepcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsNew() As Boolean
            Get
                Return Me.IsNewField
            End Get
            Set
                If (Me.IsNewField.Equals(value) <> true) Then
                    Me.IsNewField = value
                    Me.RaisePropertyChanged("IsNew")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mensaje() As String
            Get
                Return Me.MensajeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeField, value) <> true) Then
                    Me.MensajeField = value
                    Me.RaisePropertyChanged("Mensaje")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Propietario() As String
            Get
                Return Me.PropietarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PropietarioField, value) <> true) Then
                    Me.PropietarioField = value
                    Me.RaisePropertyChanged("Propietario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Regla() As String
            Get
                Return Me.ReglaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReglaField, value) <> true) Then
                    Me.ReglaField = value
                    Me.RaisePropertyChanged("Regla")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReglasDet() As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det()
            Get
                Return Me.ReglasDetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReglasDetField, value) <> true) Then
                    Me.ReglasDetField = value
                    Me.RaisePropertyChanged("ReglasDet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property User_agr() As String
            Get
                Return Me.User_agrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.User_agrField, value) <> true) Then
                    Me.User_agrField = value
                    Me.RaisePropertyChanged("User_agr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property User_mod() As String
            Get
                Return Me.User_modField
            End Get
            Set
                If (Object.ReferenceEquals(Me.User_modField, value) <> true) Then
                    Me.User_modField = value
                    Me.RaisePropertyChanged("User_mod")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="clsBePropietario_reglas_det", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class clsBePropietario_reglas_det
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fec_agrField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Fec_modField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdDestinatarioPropietarioField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdReglaPropietarioDetField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdReglaPropietarioEncField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsNewField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreDestinatarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private User_agrField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private User_modField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fec_agr() As Date
            Get
                Return Me.Fec_agrField
            End Get
            Set
                If (Me.Fec_agrField.Equals(value) <> true) Then
                    Me.Fec_agrField = value
                    Me.RaisePropertyChanged("Fec_agr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fec_mod() As Date
            Get
                Return Me.Fec_modField
            End Get
            Set
                If (Me.Fec_modField.Equals(value) <> true) Then
                    Me.Fec_modField = value
                    Me.RaisePropertyChanged("Fec_mod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdDestinatarioPropietario() As Integer
            Get
                Return Me.IdDestinatarioPropietarioField
            End Get
            Set
                If (Me.IdDestinatarioPropietarioField.Equals(value) <> true) Then
                    Me.IdDestinatarioPropietarioField = value
                    Me.RaisePropertyChanged("IdDestinatarioPropietario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdReglaPropietarioDet() As Integer
            Get
                Return Me.IdReglaPropietarioDetField
            End Get
            Set
                If (Me.IdReglaPropietarioDetField.Equals(value) <> true) Then
                    Me.IdReglaPropietarioDetField = value
                    Me.RaisePropertyChanged("IdReglaPropietarioDet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdReglaPropietarioEnc() As Integer
            Get
                Return Me.IdReglaPropietarioEncField
            End Get
            Set
                If (Me.IdReglaPropietarioEncField.Equals(value) <> true) Then
                    Me.IdReglaPropietarioEncField = value
                    Me.RaisePropertyChanged("IdReglaPropietarioEnc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsNew() As Boolean
            Get
                Return Me.IsNewField
            End Get
            Set
                If (Me.IsNewField.Equals(value) <> true) Then
                    Me.IsNewField = value
                    Me.RaisePropertyChanged("IsNew")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreDestinatario() As String
            Get
                Return Me.NombreDestinatarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreDestinatarioField, value) <> true) Then
                    Me.NombreDestinatarioField = value
                    Me.RaisePropertyChanged("NombreDestinatario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property User_agr() As String
            Get
                Return Me.User_agrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.User_agrField, value) <> true) Then
                    Me.User_agrField = value
                    Me.RaisePropertyChanged("User_agr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property User_mod() As String
            Get
                Return Me.User_modField
            End Get
            Set
                If (Object.ReferenceEquals(Me.User_modField, value) <> true) Then
                    Me.User_modField = value
                    Me.RaisePropertyChanged("User_mod")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion")>  _
    Public Interface IServicePropietarioReglaRecepcion
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/Guarda", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GuardaResponse")>  _
        Sub Guarda(ByVal pObjRE As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc, ByVal pListObjR() As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/Guarda", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GuardaResponse")>  _
        Function GuardaAsync(ByVal pObjRE As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc, ByVal pListObjR() As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetSingle", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetSingleResponse")>  _
        Function GetSingle(ByVal pIdReglaPropietarioEnc As Integer) As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetSingle", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetSingleResponse")>  _
        Function GetSingleAsync(ByVal pIdReglaPropietarioEnc As Integer) As System.Threading.Tasks.Task(Of WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllByEncabezado", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllByEncabezadoResponse")>  _
        Function GetAllByEncabezado(ByVal pIdReglaPropietarioEnc As Integer) As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllByEncabezado", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllByEncabezadoResponse")>  _
        Function GetAllByEncabezadoAsync(ByVal pIdReglaPropietarioEnc As Integer) As System.Threading.Tasks.Task(Of WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllDet", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllDetResponse")>  _
        Function GetAllDet() As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllDet", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllDetResponse")>  _
        Function GetAllDetAsync() As System.Threading.Tasks.Task(Of WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllByPropietario", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllByPropietarioResponse")>  _
        Function GetAllByPropietario(ByVal pIdPropietario As Integer) As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllByPropietario", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/GetAllByPropietarioResponse")>  _
        Function GetAllByPropietarioAsync(ByVal pIdPropietario As Integer) As System.Threading.Tasks.Task(Of WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/DesactivarRegla", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/DesactivarReglaResponse")>  _
        Sub DesactivarRegla(ByVal pIdReglaPropietarioEnc As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/DesactivarRegla", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/DesactivarReglaResponse")>  _
        Function DesactivarReglaAsync(ByVal pIdReglaPropietarioEnc As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/Desactivar", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/DesactivarResponse")>  _
        Sub Desactivar(ByVal pIdReglaPropietarioDet As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/Desactivar", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/DesactivarResponse")>  _
        Function DesactivarAsync(ByVal pIdReglaPropietarioDet As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/ExisteRegla", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/ExisteReglaResponse")>  _
        Function ExisteRegla(ByVal pIdReglaRecepcion As Integer, ByVal pIdPropietario As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicePropietarioReglaRecepcion/ExisteRegla", ReplyAction:="http://tempuri.org/IServicePropietarioReglaRecepcion/ExisteReglaResponse")>  _
        Function ExisteReglaAsync(ByVal pIdReglaRecepcion As Integer, ByVal pIdPropietario As Integer) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServicePropietarioReglaRecepcionChannel
        Inherits WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicePropietarioReglaRecepcionClient
        Inherits System.ServiceModel.ClientBase(Of WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion)
        Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub Guarda(ByVal pObjRE As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc, ByVal pListObjR() As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det) Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.Guarda
            MyBase.Channel.Guarda(pObjRE, pListObjR)
        End Sub
        
        Public Function GuardaAsync(ByVal pObjRE As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc, ByVal pListObjR() As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det) As System.Threading.Tasks.Task Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.GuardaAsync
            Return MyBase.Channel.GuardaAsync(pObjRE, pListObjR)
        End Function
        
        Public Function GetSingle(ByVal pIdReglaPropietarioEnc As Integer) As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.GetSingle
            Return MyBase.Channel.GetSingle(pIdReglaPropietarioEnc)
        End Function
        
        Public Function GetSingleAsync(ByVal pIdReglaPropietarioEnc As Integer) As System.Threading.Tasks.Task(Of WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc) Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.GetSingleAsync
            Return MyBase.Channel.GetSingleAsync(pIdReglaPropietarioEnc)
        End Function
        
        Public Function GetAllByEncabezado(ByVal pIdReglaPropietarioEnc As Integer) As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det() Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.GetAllByEncabezado
            Return MyBase.Channel.GetAllByEncabezado(pIdReglaPropietarioEnc)
        End Function
        
        Public Function GetAllByEncabezadoAsync(ByVal pIdReglaPropietarioEnc As Integer) As System.Threading.Tasks.Task(Of WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det()) Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.GetAllByEncabezadoAsync
            Return MyBase.Channel.GetAllByEncabezadoAsync(pIdReglaPropietarioEnc)
        End Function
        
        Public Function GetAllDet() As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det() Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.GetAllDet
            Return MyBase.Channel.GetAllDet
        End Function
        
        Public Function GetAllDetAsync() As System.Threading.Tasks.Task(Of WCFPropietarioReglaRecepcion.clsBePropietario_reglas_det()) Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.GetAllDetAsync
            Return MyBase.Channel.GetAllDetAsync
        End Function
        
        Public Function GetAllByPropietario(ByVal pIdPropietario As Integer) As WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc() Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.GetAllByPropietario
            Return MyBase.Channel.GetAllByPropietario(pIdPropietario)
        End Function
        
        Public Function GetAllByPropietarioAsync(ByVal pIdPropietario As Integer) As System.Threading.Tasks.Task(Of WCFPropietarioReglaRecepcion.clsBePropietario_reglas_enc()) Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.GetAllByPropietarioAsync
            Return MyBase.Channel.GetAllByPropietarioAsync(pIdPropietario)
        End Function
        
        Public Sub DesactivarRegla(ByVal pIdReglaPropietarioEnc As Integer) Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.DesactivarRegla
            MyBase.Channel.DesactivarRegla(pIdReglaPropietarioEnc)
        End Sub
        
        Public Function DesactivarReglaAsync(ByVal pIdReglaPropietarioEnc As Integer) As System.Threading.Tasks.Task Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.DesactivarReglaAsync
            Return MyBase.Channel.DesactivarReglaAsync(pIdReglaPropietarioEnc)
        End Function
        
        Public Sub Desactivar(ByVal pIdReglaPropietarioDet As Integer) Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.Desactivar
            MyBase.Channel.Desactivar(pIdReglaPropietarioDet)
        End Sub
        
        Public Function DesactivarAsync(ByVal pIdReglaPropietarioDet As Integer) As System.Threading.Tasks.Task Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.DesactivarAsync
            Return MyBase.Channel.DesactivarAsync(pIdReglaPropietarioDet)
        End Function
        
        Public Function ExisteRegla(ByVal pIdReglaRecepcion As Integer, ByVal pIdPropietario As Integer) As Boolean Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.ExisteRegla
            Return MyBase.Channel.ExisteRegla(pIdReglaRecepcion, pIdPropietario)
        End Function
        
        Public Function ExisteReglaAsync(ByVal pIdReglaRecepcion As Integer, ByVal pIdPropietario As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements WCFPropietarioReglaRecepcion.IServicePropietarioReglaRecepcion.ExisteReglaAsync
            Return MyBase.Channel.ExisteReglaAsync(pIdReglaRecepcion, pIdPropietario)
        End Function
    End Class
End Namespace
