#1-QUICKTAG-DEMO
SERVIDOR_BD_WMS = LAPTOP-5GDJFUCN\PROGRAX
NOMBRE_BD_WMS = TOMWMS_QUICKTAG
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
FORMATO_DESPACHO = 3
TIMEOUT_BD_ERP = 0
ID_EMPRESA_QUICKTAG= 1
ID_STANDALONE = 0
IMPRESORA_DEFAULT=ZDesigner ZT411-203dpi ZPL
#FIN