'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSOrdenesProduccion
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="OP_Lanzadas_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/op_lanzadas")>  _
    Partial Public Class OP_Lanzadas_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ReadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadByRecIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsUpdatedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRecIdFromKeyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Delete_ProdOrderLinesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.TOMWMS.My.MySettings.Default.NavSync_WSOrdenesProduccion_OP_Lanzadas_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ReadCompleted As ReadCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadByRecIdCompleted As ReadByRecIdCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadMultipleCompleted As ReadMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event IsUpdatedCompleted As IsUpdatedCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRecIdFromKeyCompleted As GetRecIdFromKeyCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateCompleted As CreateCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateMultipleCompleted As CreateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCompleted As UpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateMultipleCompleted As UpdateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCompleted As DeleteCompletedEventHandler
        
        '''<remarks/>
        Public Event Delete_ProdOrderLinesCompleted As Delete_ProdOrderLinesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal No As String) As <System.Xml.Serialization.XmlElementAttribute("OP_Lanzadas")> OP_Lanzadas
            Dim results() As Object = Me.Invoke("Read", New Object() {No})
            Return CType(results(0),OP_Lanzadas)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal No As String)
            Me.ReadAsync(No, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal No As String, ByVal userState As Object)
            If (Me.ReadOperationCompleted Is Nothing) Then
                Me.ReadOperationCompleted = AddressOf Me.OnReadOperationCompleted
            End If
            Me.InvokeAsync("Read", New Object() {No}, Me.ReadOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadCompleted(Me, New ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("OP_Lanzadas")> OP_Lanzadas
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),OP_Lanzadas)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String)
            Me.ReadByRecIdAsync(recId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String, ByVal userState As Object)
            If (Me.ReadByRecIdOperationCompleted Is Nothing) Then
                Me.ReadByRecIdOperationCompleted = AddressOf Me.OnReadByRecIdOperationCompleted
            End If
            Me.InvokeAsync("ReadByRecId", New Object() {recId}, Me.ReadByRecIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadByRecIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadByRecIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadByRecIdCompleted(Me, New ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As OP_Lanzadas_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> OP_Lanzadas()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),OP_Lanzadas())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As OP_Lanzadas_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer)
            Me.ReadMultipleAsync(filter, bookmarkKey, setSize, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As OP_Lanzadas_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal userState As Object)
            If (Me.ReadMultipleOperationCompleted Is Nothing) Then
                Me.ReadMultipleOperationCompleted = AddressOf Me.OnReadMultipleOperationCompleted
            End If
            Me.InvokeAsync("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, Me.ReadMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadMultipleCompleted(Me, New ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String)
            Me.IsUpdatedAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.IsUpdatedOperationCompleted Is Nothing) Then
                Me.IsUpdatedOperationCompleted = AddressOf Me.OnIsUpdatedOperationCompleted
            End If
            Me.InvokeAsync("IsUpdated", New Object() {Key}, Me.IsUpdatedOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsUpdatedOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsUpdatedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsUpdatedCompleted(Me, New IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String)
            Me.GetRecIdFromKeyAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.GetRecIdFromKeyOperationCompleted Is Nothing) Then
                Me.GetRecIdFromKeyOperationCompleted = AddressOf Me.OnGetRecIdFromKeyOperationCompleted
            End If
            Me.InvokeAsync("GetRecIdFromKey", New Object() {Key}, Me.GetRecIdFromKeyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRecIdFromKeyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRecIdFromKeyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRecIdFromKeyCompleted(Me, New GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:Create", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="Create_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Create(ByRef OP_Lanzadas As OP_Lanzadas)
            Dim results() As Object = Me.Invoke("Create", New Object() {OP_Lanzadas})
            OP_Lanzadas = CType(results(0),OP_Lanzadas)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal OP_Lanzadas As OP_Lanzadas)
            Me.CreateAsync(OP_Lanzadas, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal OP_Lanzadas As OP_Lanzadas, ByVal userState As Object)
            If (Me.CreateOperationCompleted Is Nothing) Then
                Me.CreateOperationCompleted = AddressOf Me.OnCreateOperationCompleted
            End If
            Me.InvokeAsync("Create", New Object() {OP_Lanzadas}, Me.CreateOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCompleted(Me, New CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:CreateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="CreateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef OP_Lanzadas_List() As OP_Lanzadas)
            Dim results() As Object = Me.Invoke("CreateMultiple", New Object() {OP_Lanzadas_List})
            OP_Lanzadas_List = CType(results(0),OP_Lanzadas())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal OP_Lanzadas_List() As OP_Lanzadas)
            Me.CreateMultipleAsync(OP_Lanzadas_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal OP_Lanzadas_List() As OP_Lanzadas, ByVal userState As Object)
            If (Me.CreateMultipleOperationCompleted Is Nothing) Then
                Me.CreateMultipleOperationCompleted = AddressOf Me.OnCreateMultipleOperationCompleted
            End If
            Me.InvokeAsync("CreateMultiple", New Object() {OP_Lanzadas_List}, Me.CreateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateMultipleCompleted(Me, New CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef OP_Lanzadas As OP_Lanzadas)
            Dim results() As Object = Me.Invoke("Update", New Object() {OP_Lanzadas})
            OP_Lanzadas = CType(results(0),OP_Lanzadas)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal OP_Lanzadas As OP_Lanzadas)
            Me.UpdateAsync(OP_Lanzadas, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal OP_Lanzadas As OP_Lanzadas, ByVal userState As Object)
            If (Me.UpdateOperationCompleted Is Nothing) Then
                Me.UpdateOperationCompleted = AddressOf Me.OnUpdateOperationCompleted
            End If
            Me.InvokeAsync("Update", New Object() {OP_Lanzadas}, Me.UpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCompleted(Me, New UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef OP_Lanzadas_List() As OP_Lanzadas)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {OP_Lanzadas_List})
            OP_Lanzadas_List = CType(results(0),OP_Lanzadas())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal OP_Lanzadas_List() As OP_Lanzadas)
            Me.UpdateMultipleAsync(OP_Lanzadas_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal OP_Lanzadas_List() As OP_Lanzadas, ByVal userState As Object)
            If (Me.UpdateMultipleOperationCompleted Is Nothing) Then
                Me.UpdateMultipleOperationCompleted = AddressOf Me.OnUpdateMultipleOperationCompleted
            End If
            Me.InvokeAsync("UpdateMultiple", New Object() {OP_Lanzadas_List}, Me.UpdateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateMultipleCompleted(Me, New UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:Delete", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="Delete_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String)
            Me.DeleteAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.DeleteOperationCompleted Is Nothing) Then
                Me.DeleteOperationCompleted = AddressOf Me.OnDeleteOperationCompleted
            End If
            Me.InvokeAsync("Delete", New Object() {Key}, Me.DeleteOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCompleted(Me, New DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/op_lanzadas:Delete_ProdOrderLines", RequestNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", ResponseElementName:="Delete_ProdOrderLines_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/op_lanzadas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete_ProdOrderLines(ByVal ProdOrderLines_Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_ProdOrderLines_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete_ProdOrderLines", New Object() {ProdOrderLines_Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Delete_ProdOrderLinesAsync(ByVal ProdOrderLines_Key As String)
            Me.Delete_ProdOrderLinesAsync(ProdOrderLines_Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Delete_ProdOrderLinesAsync(ByVal ProdOrderLines_Key As String, ByVal userState As Object)
            If (Me.Delete_ProdOrderLinesOperationCompleted Is Nothing) Then
                Me.Delete_ProdOrderLinesOperationCompleted = AddressOf Me.OnDelete_ProdOrderLinesOperationCompleted
            End If
            Me.InvokeAsync("Delete_ProdOrderLines", New Object() {ProdOrderLines_Key}, Me.Delete_ProdOrderLinesOperationCompleted, userState)
        End Sub
        
        Private Sub OnDelete_ProdOrderLinesOperationCompleted(ByVal arg As Object)
            If (Not (Me.Delete_ProdOrderLinesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Delete_ProdOrderLinesCompleted(Me, New Delete_ProdOrderLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/op_lanzadas")>  _
    Partial Public Class OP_Lanzadas
        
        Private keyField As String
        
        Private noField As String
        
        Private descriptionField As String
        
        Private description_2Field As String
        
        Private source_TypeField As Source_Type
        
        Private source_TypeFieldSpecified As Boolean
        
        Private source_NoField As String
        
        Private search_DescriptionField As String
        
        Private quantityField As Decimal
        
        Private quantityFieldSpecified As Boolean
        
        Private due_DateField As Date
        
        Private due_DateFieldSpecified As Boolean
        
        Private assigned_User_IDField As String
        
        Private blockedField As Boolean
        
        Private blockedFieldSpecified As Boolean
        
        Private last_Date_ModifiedField As Date
        
        Private last_Date_ModifiedFieldSpecified As Boolean
        
        Private routing_NoField As String
        
        Private starting_TimeField As Date
        
        Private starting_TimeFieldSpecified As Boolean
        
        Private starting_DateField As Date
        
        Private starting_DateFieldSpecified As Boolean
        
        Private ending_TimeField As Date
        
        Private ending_TimeFieldSpecified As Boolean
        
        Private ending_DateField As Date
        
        Private ending_DateFieldSpecified As Boolean
        
        Private inventory_Posting_GroupField As String
        
        Private gen_Prod_Posting_GroupField As String
        
        Private gen_Bus_Posting_GroupField As String
        
        Private shortcut_Dimension_1_CodeField As String
        
        Private shortcut_Dimension_2_CodeField As String
        
        Private location_CodeField As String
        
        Private bin_CodeField As String
        
        Private prodOrderLinesField() As Released_Prod_Order_Lines
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property No() As String
            Get
                Return Me.noField
            End Get
            Set
                Me.noField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description_2() As String
            Get
                Return Me.description_2Field
            End Get
            Set
                Me.description_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Source_Type() As Source_Type
            Get
                Return Me.source_TypeField
            End Get
            Set
                Me.source_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Source_TypeSpecified() As Boolean
            Get
                Return Me.source_TypeFieldSpecified
            End Get
            Set
                Me.source_TypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Source_No() As String
            Get
                Return Me.source_NoField
            End Get
            Set
                Me.source_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Search_Description() As String
            Get
                Return Me.search_DescriptionField
            End Get
            Set
                Me.search_DescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity() As Decimal
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QuantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Due_Date() As Date
            Get
                Return Me.due_DateField
            End Get
            Set
                Me.due_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Due_DateSpecified() As Boolean
            Get
                Return Me.due_DateFieldSpecified
            End Get
            Set
                Me.due_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Assigned_User_ID() As String
            Get
                Return Me.assigned_User_IDField
            End Get
            Set
                Me.assigned_User_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Blocked() As Boolean
            Get
                Return Me.blockedField
            End Get
            Set
                Me.blockedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property BlockedSpecified() As Boolean
            Get
                Return Me.blockedFieldSpecified
            End Get
            Set
                Me.blockedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Last_Date_Modified() As Date
            Get
                Return Me.last_Date_ModifiedField
            End Get
            Set
                Me.last_Date_ModifiedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Last_Date_ModifiedSpecified() As Boolean
            Get
                Return Me.last_Date_ModifiedFieldSpecified
            End Get
            Set
                Me.last_Date_ModifiedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Routing_No() As String
            Get
                Return Me.routing_NoField
            End Get
            Set
                Me.routing_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="time")>  _
        Public Property Starting_Time() As Date
            Get
                Return Me.starting_TimeField
            End Get
            Set
                Me.starting_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Starting_TimeSpecified() As Boolean
            Get
                Return Me.starting_TimeFieldSpecified
            End Get
            Set
                Me.starting_TimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Starting_Date() As Date
            Get
                Return Me.starting_DateField
            End Get
            Set
                Me.starting_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Starting_DateSpecified() As Boolean
            Get
                Return Me.starting_DateFieldSpecified
            End Get
            Set
                Me.starting_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="time")>  _
        Public Property Ending_Time() As Date
            Get
                Return Me.ending_TimeField
            End Get
            Set
                Me.ending_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Ending_TimeSpecified() As Boolean
            Get
                Return Me.ending_TimeFieldSpecified
            End Get
            Set
                Me.ending_TimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Ending_Date() As Date
            Get
                Return Me.ending_DateField
            End Get
            Set
                Me.ending_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Ending_DateSpecified() As Boolean
            Get
                Return Me.ending_DateFieldSpecified
            End Get
            Set
                Me.ending_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Inventory_Posting_Group() As String
            Get
                Return Me.inventory_Posting_GroupField
            End Get
            Set
                Me.inventory_Posting_GroupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Gen_Prod_Posting_Group() As String
            Get
                Return Me.gen_Prod_Posting_GroupField
            End Get
            Set
                Me.gen_Prod_Posting_GroupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Gen_Bus_Posting_Group() As String
            Get
                Return Me.gen_Bus_Posting_GroupField
            End Get
            Set
                Me.gen_Bus_Posting_GroupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_1_Code() As String
            Get
                Return Me.shortcut_Dimension_1_CodeField
            End Get
            Set
                Me.shortcut_Dimension_1_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_2_Code() As String
            Get
                Return Me.shortcut_Dimension_2_CodeField
            End Get
            Set
                Me.shortcut_Dimension_2_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Location_Code() As String
            Get
                Return Me.location_CodeField
            End Get
            Set
                Me.location_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bin_Code() As String
            Get
                Return Me.bin_CodeField
            End Get
            Set
                Me.bin_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property ProdOrderLines() As Released_Prod_Order_Lines()
            Get
                Return Me.prodOrderLinesField
            End Get
            Set
                Me.prodOrderLinesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/op_lanzadas")>  _
    Public Enum Source_Type
        
        '''<remarks/>
        Item
        
        '''<remarks/>
        Family
        
        '''<remarks/>
        Sales_Header
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/op_lanzadas")>  _
    Partial Public Class Released_Prod_Order_Lines
        
        Private keyField As String
        
        Private item_NoField As String
        
        Private variant_CodeField As String
        
        Private due_DateField As Date
        
        Private due_DateFieldSpecified As Boolean
        
        Private planning_FlexibilityField As Planning_Flexibility
        
        Private planning_FlexibilityFieldSpecified As Boolean
        
        Private descriptionField As String
        
        Private description_2Field As String
        
        Private production_BOM_NoField As String
        
        Private routing_NoField As String
        
        Private routing_Version_CodeField As String
        
        Private production_BOM_Version_CodeField As String
        
        Private location_CodeField As String
        
        Private bin_CodeField As String
        
        Private starting_Date_TimeField As Date
        
        Private starting_Date_TimeFieldSpecified As Boolean
        
        Private starting_TimeField As Date
        
        Private starting_TimeFieldSpecified As Boolean
        
        Private starting_DateField As Date
        
        Private starting_DateFieldSpecified As Boolean
        
        Private ending_Date_TimeField As Date
        
        Private ending_Date_TimeFieldSpecified As Boolean
        
        Private ending_TimeField As Date
        
        Private ending_TimeFieldSpecified As Boolean
        
        Private ending_DateField As Date
        
        Private ending_DateFieldSpecified As Boolean
        
        Private scrap_PercentField As Decimal
        
        Private scrap_PercentFieldSpecified As Boolean
        
        Private quantityField As Decimal
        
        Private quantityFieldSpecified As Boolean
        
        Private reserved_QuantityField As Decimal
        
        Private reserved_QuantityFieldSpecified As Boolean
        
        Private unit_of_Measure_CodeField As String
        
        Private finished_QuantityField As Decimal
        
        Private finished_QuantityFieldSpecified As Boolean
        
        Private remaining_QuantityField As Decimal
        
        Private remaining_QuantityFieldSpecified As Boolean
        
        Private unit_CostField As Decimal
        
        Private unit_CostFieldSpecified As Boolean
        
        Private cost_AmountField As Decimal
        
        Private cost_AmountFieldSpecified As Boolean
        
        Private shortcut_Dimension_1_CodeField As String
        
        Private shortcut_Dimension_2_CodeField As String
        
        Private shortcutDimCode3Field As String
        
        Private shortcutDimCode4Field As String
        
        Private shortcutDimCode5Field As String
        
        Private shortcutDimCode6Field As String
        
        Private shortcutDimCode7Field As String
        
        Private shortcutDimCode8Field As String
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Item_No() As String
            Get
                Return Me.item_NoField
            End Get
            Set
                Me.item_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Variant_Code() As String
            Get
                Return Me.variant_CodeField
            End Get
            Set
                Me.variant_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Due_Date() As Date
            Get
                Return Me.due_DateField
            End Get
            Set
                Me.due_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Due_DateSpecified() As Boolean
            Get
                Return Me.due_DateFieldSpecified
            End Get
            Set
                Me.due_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Planning_Flexibility() As Planning_Flexibility
            Get
                Return Me.planning_FlexibilityField
            End Get
            Set
                Me.planning_FlexibilityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Planning_FlexibilitySpecified() As Boolean
            Get
                Return Me.planning_FlexibilityFieldSpecified
            End Get
            Set
                Me.planning_FlexibilityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description_2() As String
            Get
                Return Me.description_2Field
            End Get
            Set
                Me.description_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Production_BOM_No() As String
            Get
                Return Me.production_BOM_NoField
            End Get
            Set
                Me.production_BOM_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Routing_No() As String
            Get
                Return Me.routing_NoField
            End Get
            Set
                Me.routing_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Routing_Version_Code() As String
            Get
                Return Me.routing_Version_CodeField
            End Get
            Set
                Me.routing_Version_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Production_BOM_Version_Code() As String
            Get
                Return Me.production_BOM_Version_CodeField
            End Get
            Set
                Me.production_BOM_Version_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Location_Code() As String
            Get
                Return Me.location_CodeField
            End Get
            Set
                Me.location_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bin_Code() As String
            Get
                Return Me.bin_CodeField
            End Get
            Set
                Me.bin_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Starting_Date_Time() As Date
            Get
                Return Me.starting_Date_TimeField
            End Get
            Set
                Me.starting_Date_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Starting_Date_TimeSpecified() As Boolean
            Get
                Return Me.starting_Date_TimeFieldSpecified
            End Get
            Set
                Me.starting_Date_TimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="time")>  _
        Public Property Starting_Time() As Date
            Get
                Return Me.starting_TimeField
            End Get
            Set
                Me.starting_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Starting_TimeSpecified() As Boolean
            Get
                Return Me.starting_TimeFieldSpecified
            End Get
            Set
                Me.starting_TimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Starting_Date() As Date
            Get
                Return Me.starting_DateField
            End Get
            Set
                Me.starting_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Starting_DateSpecified() As Boolean
            Get
                Return Me.starting_DateFieldSpecified
            End Get
            Set
                Me.starting_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ending_Date_Time() As Date
            Get
                Return Me.ending_Date_TimeField
            End Get
            Set
                Me.ending_Date_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Ending_Date_TimeSpecified() As Boolean
            Get
                Return Me.ending_Date_TimeFieldSpecified
            End Get
            Set
                Me.ending_Date_TimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="time")>  _
        Public Property Ending_Time() As Date
            Get
                Return Me.ending_TimeField
            End Get
            Set
                Me.ending_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Ending_TimeSpecified() As Boolean
            Get
                Return Me.ending_TimeFieldSpecified
            End Get
            Set
                Me.ending_TimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Ending_Date() As Date
            Get
                Return Me.ending_DateField
            End Get
            Set
                Me.ending_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Ending_DateSpecified() As Boolean
            Get
                Return Me.ending_DateFieldSpecified
            End Get
            Set
                Me.ending_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Scrap_Percent() As Decimal
            Get
                Return Me.scrap_PercentField
            End Get
            Set
                Me.scrap_PercentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Scrap_PercentSpecified() As Boolean
            Get
                Return Me.scrap_PercentFieldSpecified
            End Get
            Set
                Me.scrap_PercentFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity() As Decimal
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QuantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reserved_Quantity() As Decimal
            Get
                Return Me.reserved_QuantityField
            End Get
            Set
                Me.reserved_QuantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Reserved_QuantitySpecified() As Boolean
            Get
                Return Me.reserved_QuantityFieldSpecified
            End Get
            Set
                Me.reserved_QuantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Unit_of_Measure_Code() As String
            Get
                Return Me.unit_of_Measure_CodeField
            End Get
            Set
                Me.unit_of_Measure_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Finished_Quantity() As Decimal
            Get
                Return Me.finished_QuantityField
            End Get
            Set
                Me.finished_QuantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Finished_QuantitySpecified() As Boolean
            Get
                Return Me.finished_QuantityFieldSpecified
            End Get
            Set
                Me.finished_QuantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Remaining_Quantity() As Decimal
            Get
                Return Me.remaining_QuantityField
            End Get
            Set
                Me.remaining_QuantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Remaining_QuantitySpecified() As Boolean
            Get
                Return Me.remaining_QuantityFieldSpecified
            End Get
            Set
                Me.remaining_QuantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Unit_Cost() As Decimal
            Get
                Return Me.unit_CostField
            End Get
            Set
                Me.unit_CostField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Unit_CostSpecified() As Boolean
            Get
                Return Me.unit_CostFieldSpecified
            End Get
            Set
                Me.unit_CostFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cost_Amount() As Decimal
            Get
                Return Me.cost_AmountField
            End Get
            Set
                Me.cost_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Cost_AmountSpecified() As Boolean
            Get
                Return Me.cost_AmountFieldSpecified
            End Get
            Set
                Me.cost_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_1_Code() As String
            Get
                Return Me.shortcut_Dimension_1_CodeField
            End Get
            Set
                Me.shortcut_Dimension_1_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_2_Code() As String
            Get
                Return Me.shortcut_Dimension_2_CodeField
            End Get
            Set
                Me.shortcut_Dimension_2_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[3]")>  _
        Public Property ShortcutDimCode3() As String
            Get
                Return Me.shortcutDimCode3Field
            End Get
            Set
                Me.shortcutDimCode3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[4]")>  _
        Public Property ShortcutDimCode4() As String
            Get
                Return Me.shortcutDimCode4Field
            End Get
            Set
                Me.shortcutDimCode4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[5]")>  _
        Public Property ShortcutDimCode5() As String
            Get
                Return Me.shortcutDimCode5Field
            End Get
            Set
                Me.shortcutDimCode5Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[6]")>  _
        Public Property ShortcutDimCode6() As String
            Get
                Return Me.shortcutDimCode6Field
            End Get
            Set
                Me.shortcutDimCode6Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[7]")>  _
        Public Property ShortcutDimCode7() As String
            Get
                Return Me.shortcutDimCode7Field
            End Get
            Set
                Me.shortcutDimCode7Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[8]")>  _
        Public Property ShortcutDimCode8() As String
            Get
                Return Me.shortcutDimCode8Field
            End Get
            Set
                Me.shortcutDimCode8Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/op_lanzadas")>  _
    Public Enum Planning_Flexibility
        
        '''<remarks/>
        Unlimited
        
        '''<remarks/>
        None
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/op_lanzadas")>  _
    Partial Public Class OP_Lanzadas_Filter
        
        Private fieldField As OP_Lanzadas_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As OP_Lanzadas_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/op_lanzadas")>  _
    Public Enum OP_Lanzadas_Fields
        
        '''<remarks/>
        No
        
        '''<remarks/>
        Description
        
        '''<remarks/>
        Description_2
        
        '''<remarks/>
        Source_Type
        
        '''<remarks/>
        Source_No
        
        '''<remarks/>
        Search_Description
        
        '''<remarks/>
        Quantity
        
        '''<remarks/>
        Due_Date
        
        '''<remarks/>
        Assigned_User_ID
        
        '''<remarks/>
        Blocked
        
        '''<remarks/>
        Last_Date_Modified
        
        '''<remarks/>
        Routing_No
        
        '''<remarks/>
        Starting_Time
        
        '''<remarks/>
        Starting_Date
        
        '''<remarks/>
        Ending_Time
        
        '''<remarks/>
        Ending_Date
        
        '''<remarks/>
        Inventory_Posting_Group
        
        '''<remarks/>
        Gen_Prod_Posting_Group
        
        '''<remarks/>
        Gen_Bus_Posting_Group
        
        '''<remarks/>
        Shortcut_Dimension_1_Code
        
        '''<remarks/>
        Shortcut_Dimension_2_Code
        
        '''<remarks/>
        Location_Code
        
        '''<remarks/>
        Bin_Code
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReadCompletedEventHandler(ByVal sender As Object, ByVal e As ReadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OP_Lanzadas
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OP_Lanzadas)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReadByRecIdCompletedEventHandler(ByVal sender As Object, ByVal e As ReadByRecIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadByRecIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OP_Lanzadas
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OP_Lanzadas)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReadMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As ReadMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OP_Lanzadas()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OP_Lanzadas())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub IsUpdatedCompletedEventHandler(ByVal sender As Object, ByVal e As IsUpdatedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsUpdatedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetRecIdFromKeyCompletedEventHandler(ByVal sender As Object, ByVal e As GetRecIdFromKeyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRecIdFromKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CreateCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property OP_Lanzadas() As OP_Lanzadas
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OP_Lanzadas)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CreateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As CreateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property OP_Lanzadas_List() As OP_Lanzadas()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OP_Lanzadas())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub UpdateCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property OP_Lanzadas() As OP_Lanzadas
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OP_Lanzadas)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub UpdateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property OP_Lanzadas_List() As OP_Lanzadas()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OP_Lanzadas())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub DeleteCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Delete_ProdOrderLinesCompletedEventHandler(ByVal sender As Object, ByVal e As Delete_ProdOrderLinesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Delete_ProdOrderLinesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
