DEBUG = OFF


#CEALSA - TMS_LOCAL
SERVIDOR_BD_WMS = 192.168.0.98
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAP
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 3
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbpruebas
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
TIMEOUT_BD_ERP = 0
#FIN

#CEALSA - SERVER_PRD
SERVIDOR_BD_WMS = 192.168.0.98
NOMBRE_BD_WMS = IMS4MB_CEALSA_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 3
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbpruebas
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
TIMEOUT_BD_ERP = 0
#FIN

#CEALSA - SERVER_QAS
SERVIDOR_BD_WMS = 192.168.0.98
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAS
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 3
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbpruebas
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
TIMEOUT_BD_ERP = 0
#FIN
