DEBUG = OFF

#CEALSA - TMS_SERVER
SERVIDOR_BD_WMS = 192.168.1.60
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAP
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 3
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbpruebas
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
ID_EMPRESA_TMS = 0
TIMEOUT_BD_ERP = 0
ID_EMPRESA_TMS = 1
#FIN
