param(
    [string]$RepoRoot = "C:\Users\yejc2\source\repos\wms-brain",
    [string]$Branch = "origin/wms-db-brain",
    [string]$OutputPath = "wms-brain/brain/_index/DB-BRAIN-BRANCH-MANIFEST.yml",
    [switch]$Fetch
)

$ErrorActionPreference = "Stop"

Push-Location $RepoRoot
try {
    if ($Fetch) {
        git fetch origin wms-db-brain | Out-Host
    }

    $files = git -c core.quotepath=false ls-tree -r --name-only $Branch -- db-brain
    if (-not $files) {
        throw "No db-brain files found in $Branch"
    }

    $groups = [ordered]@{
        tables = @($files | Where-Object { $_ -like "db-brain/tables/*.md" -and $_ -notlike "*/_index.md" })
        views = @($files | Where-Object { $_ -like "db-brain/views/*.md" -and $_ -notlike "*/_index.md" })
        sps = @($files | Where-Object { $_ -like "db-brain/sps/*.md" -and $_ -notlike "*/_index.md" })
        functions = @($files | Where-Object { $_ -like "db-brain/functions/*.md" -and $_ -notlike "*/_index.md" })
        parametrizacion = @($files | Where-Object { $_ -like "db-brain/parametrizacion/*.md" })
        meta = @($files | Where-Object { $_ -like "db-brain/_meta/*" })
    }

    $stats = git show "$Branch`:db-brain/_meta/stats.md"
    $officialCounts = @{}
    foreach ($line in $stats) {
        if ($line -match '^\| (?:\*\*)?`?([^`*]+)`?(?:\*\*)? \| (?:\*\*)?([0-9]+)(?:\*\*)? \|$') {
            $officialCounts[$Matches[1]] = [int]$Matches[2]
        }
    }
    $topTables = @()
    foreach ($line in $stats) {
        if ($line -match '^\| `([^`]+)` \| ([0-9.]+) \| ([0-9-]+) \|$') {
            $topTables += [pscustomobject]@{
                name = $Matches[1]
                rows = $Matches[2]
                modify_date = $Matches[3]
            }
        }
    }

    $outFull = Join-Path $RepoRoot $OutputPath
    $outDir = Split-Path -Parent $outFull
    if (-not (Test-Path $outDir)) {
        New-Item -ItemType Directory -Path $outDir | Out-Null
    }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by wms-db-brain-inventory.ps1")
    $lines.Add("# #EJC20260527: compact manifest for selective use of origin/wms-db-brain.")
    $lines.Add("snapshot_branch: $Branch")
    $lines.Add("snapshot_root: db-brain")
    $lines.Add("generated_at: '$((Get-Date).ToString("s"))'")
    $lines.Add("counts:")
    $lines.Add("  user_tables: $($officialCounts['USER_TABLE'])")
    $lines.Add("  views: $($officialCounts['VIEW'])")
    $lines.Add("  stored_procedures: $($officialCounts['SQL_STORED_PROCEDURE'])")
    $lines.Add("  scalar_functions: $($officialCounts['SQL_SCALAR_FUNCTION'])")
    $lines.Add("  total_sql_objects: $($officialCounts['TOTAL'])")
    $lines.Add("  parametrizacion_files: $($groups['parametrizacion'].Count)")
    $lines.Add("  meta_files: $($groups['meta'].Count)")
    $lines.Add("high_value_paths:")
    foreach ($path in @(
        "db-brain/_meta/stats.md",
        "db-brain/parametrizacion/README.md",
        "db-brain/parametrizacion/flags-bodega.md",
        "db-brain/parametrizacion/flags-producto.md",
        "db-brain/parametrizacion/matriz-killios.md",
        "db-brain/tables/trans_movimientos.md",
        "db-brain/tables/stock.md",
        "db-brain/tables/stock_res.md",
        "db-brain/tables/trans_picking_ubic.md",
        "db-brain/tables/trans_picking_ubic_stock.md",
        "db-brain/tables/trans_pe_det.md"
    )) {
        $lines.Add("  - $path")
    }
    $lines.Add("top_tables_by_rows:")
    foreach ($table in $topTables | Select-Object -First 15) {
        $lines.Add("  - name: $($table.name)")
        $lines.Add("    rows: '$($table.rows)'")
        $lines.Add("    modify_date: '$($table.modify_date)'")
    }

    [System.IO.File]::WriteAllLines($outFull, $lines, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Wrote $OutputPath"
}
finally {
    Pop-Location
}
