//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOMWMS.srvBarrasPallet {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsBeI_nav_barras_pallet", Namespace="http://schemas.datacontract.org/2004/07/TOMWMS")]
    [System.SerializableAttribute()]
    public partial class clsBeI_nav_barras_pallet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Bodega_DestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Bodega_OrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cajas_Por_CamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Camas_Por_TarimaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Cantidad_PresentacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Cantidad_UMPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_barraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_AgregadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_IngresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_ProduccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_VenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPalletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRecepcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Lote_NumericoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RecibidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UM_ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bodega_Destino {
            get {
                return this.Bodega_DestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.Bodega_DestinoField, value) != true)) {
                    this.Bodega_DestinoField = value;
                    this.RaisePropertyChanged("Bodega_Destino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bodega_Origen {
            get {
                return this.Bodega_OrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.Bodega_OrigenField, value) != true)) {
                    this.Bodega_OrigenField = value;
                    this.RaisePropertyChanged("Bodega_Origen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cajas_Por_Cama {
            get {
                return this.Cajas_Por_CamaField;
            }
            set {
                if ((this.Cajas_Por_CamaField.Equals(value) != true)) {
                    this.Cajas_Por_CamaField = value;
                    this.RaisePropertyChanged("Cajas_Por_Cama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Camas_Por_Tarima {
            get {
                return this.Camas_Por_TarimaField;
            }
            set {
                if ((this.Camas_Por_TarimaField.Equals(value) != true)) {
                    this.Camas_Por_TarimaField = value;
                    this.RaisePropertyChanged("Camas_Por_Tarima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad_Presentacion {
            get {
                return this.Cantidad_PresentacionField;
            }
            set {
                if ((this.Cantidad_PresentacionField.Equals(value) != true)) {
                    this.Cantidad_PresentacionField = value;
                    this.RaisePropertyChanged("Cantidad_Presentacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad_UMP {
            get {
                return this.Cantidad_UMPField;
            }
            set {
                if ((this.Cantidad_UMPField.Equals(value) != true)) {
                    this.Cantidad_UMPField = value;
                    this.RaisePropertyChanged("Cantidad_UMP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo_barra {
            get {
                return this.Codigo_barraField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_barraField, value) != true)) {
                    this.Codigo_barraField = value;
                    this.RaisePropertyChanged("Codigo_barra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Agregado {
            get {
                return this.Fecha_AgregadoField;
            }
            set {
                if ((this.Fecha_AgregadoField.Equals(value) != true)) {
                    this.Fecha_AgregadoField = value;
                    this.RaisePropertyChanged("Fecha_Agregado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Ingreso {
            get {
                return this.Fecha_IngresoField;
            }
            set {
                if ((this.Fecha_IngresoField.Equals(value) != true)) {
                    this.Fecha_IngresoField = value;
                    this.RaisePropertyChanged("Fecha_Ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Produccion {
            get {
                return this.Fecha_ProduccionField;
            }
            set {
                if ((this.Fecha_ProduccionField.Equals(value) != true)) {
                    this.Fecha_ProduccionField = value;
                    this.RaisePropertyChanged("Fecha_Produccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Vence {
            get {
                return this.Fecha_VenceField;
            }
            set {
                if ((this.Fecha_VenceField.Equals(value) != true)) {
                    this.Fecha_VenceField = value;
                    this.RaisePropertyChanged("Fecha_Vence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPallet {
            get {
                return this.IdPalletField;
            }
            set {
                if ((this.IdPalletField.Equals(value) != true)) {
                    this.IdPalletField = value;
                    this.RaisePropertyChanged("IdPallet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRecepcion {
            get {
                return this.IdRecepcionField;
            }
            set {
                if ((this.IdRecepcionField.Equals(value) != true)) {
                    this.IdRecepcionField = value;
                    this.RaisePropertyChanged("IdRecepcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lote {
            get {
                return this.LoteField;
            }
            set {
                if ((object.ReferenceEquals(this.LoteField, value) != true)) {
                    this.LoteField = value;
                    this.RaisePropertyChanged("Lote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Lote_Numerico {
            get {
                return this.Lote_NumericoField;
            }
            set {
                if ((this.Lote_NumericoField.Equals(value) != true)) {
                    this.Lote_NumericoField = value;
                    this.RaisePropertyChanged("Lote_Numerico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Recibido {
            get {
                return this.RecibidoField;
            }
            set {
                if ((this.RecibidoField.Equals(value) != true)) {
                    this.RecibidoField = value;
                    this.RaisePropertyChanged("Recibido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UM_Producto {
            get {
                return this.UM_ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.UM_ProductoField, value) != true)) {
                    this.UM_ProductoField = value;
                    this.RaisePropertyChanged("UM_Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvBarrasPallet.IBarras_Pallet")]
    public interface IBarras_Pallet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarras_Pallet/Insert", ReplyAction="http://tempuri.org/IBarras_Pallet/InsertResponse")]
        void Insert(TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet[] pListBarras_Pallet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarras_Pallet/Insert_Single", ReplyAction="http://tempuri.org/IBarras_Pallet/Insert_SingleResponse")]
        void Insert_Single(TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet pBarra_Pallet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarras_Pallet/Update_Single", ReplyAction="http://tempuri.org/IBarras_Pallet/Update_SingleResponse")]
        void Update_Single(TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet pBarra_Pallet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarras_Pallet/Max_IdPallet", ReplyAction="http://tempuri.org/IBarras_Pallet/Max_IdPalletResponse")]
        int Max_IdPallet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarras_Pallet/Existe", ReplyAction="http://tempuri.org/IBarras_Pallet/ExisteResponse")]
        bool Existe(string Codigo_Barra_Pallet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarras_Pallet/Get_All_Activos", ReplyAction="http://tempuri.org/IBarras_Pallet/Get_All_ActivosResponse")]
        TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet[] Get_All_Activos(bool pActivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarras_Pallet/Get_All_Pendientes_Recepcion", ReplyAction="http://tempuri.org/IBarras_Pallet/Get_All_Pendientes_RecepcionResponse")]
        TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet[] Get_All_Pendientes_Recepcion(bool pActivo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBarras_PalletChannel : TOMWMS.srvBarrasPallet.IBarras_Pallet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Barras_PalletClient : System.ServiceModel.ClientBase<TOMWMS.srvBarrasPallet.IBarras_Pallet>, TOMWMS.srvBarrasPallet.IBarras_Pallet {
        
        public Barras_PalletClient() {
        }
        
        public Barras_PalletClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Barras_PalletClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Barras_PalletClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Barras_PalletClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert(TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet[] pListBarras_Pallet) {
            base.Channel.Insert(pListBarras_Pallet);
        }
        
        public void Insert_Single(TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet pBarra_Pallet) {
            base.Channel.Insert_Single(pBarra_Pallet);
        }
        
        public void Update_Single(TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet pBarra_Pallet) {
            base.Channel.Update_Single(pBarra_Pallet);
        }
        
        public int Max_IdPallet() {
            return base.Channel.Max_IdPallet();
        }
        
        public bool Existe(string Codigo_Barra_Pallet) {
            return base.Channel.Existe(Codigo_Barra_Pallet);
        }
        
        public TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet[] Get_All_Activos(bool pActivo) {
            return base.Channel.Get_All_Activos(pActivo);
        }
        
        public TOMWMS.srvBarrasPallet.clsBeI_nav_barras_pallet[] Get_All_Pendientes_Recepcion(bool pActivo) {
            return base.Channel.Get_All_Pendientes_Recepcion(pActivo);
        }
    }
}
