Imports System.Reflection
Imports DevExpress.Data
Imports DevExpress.XtraEditors
Imports DevExpress.XtraEditors.Repository
Imports DevExpress.XtraGrid
Imports DevExpress.XtraSplashScreen

Public Class frmReglaUbic

    Private pListObjT As New List(Of clsTabla)
    Public pBeReglaUbicEnc As New clsBeRegla_ubic_enc

    Public pListBEPropietarioSeleccion As New List(Of clsBePropietarioBodegaSeleccion)
    Public pListBETipoRSeleccion As New List(Of clsBeTipo_rotacion)
    Public pListBEIndiceRSeleccion As New List(Of clsBeIndice_rotacion)
    Public pListBEEstado As New List(Of clsBeProducto_estado_selection)
    Public pListBETipo As New List(Of clsBeProducto_tipo_seleccion)
    Public pListBEPres As New List(Of clsBeProducto_presentacion_sel)
    Public Delegate Sub ListarReglas()
    Public Property InvokeListarReglas As ListarReglas

    Public Enum TipoTrans
        Nuevo = 1
        Editar = 2
    End Enum

    Public Property Modo As TipoTrans
    Public Property OpcionesMenu As New clsBeOpcionesMenuRol

    Public Sub New(ByVal pModo As TipoTrans)
        InitializeComponent()
        Modo = pModo
        ' This line of code is generated by Data Source Configuration Wizard
        DgridTipoProducto.DataSource = New List(Of clsBeRegla_ubic_det_tp)()
        ' This line of code is generated by Data Source Configuration Wizard
    End Sub

    Public Sub New()
        InitializeComponent()
    End Sub

    Private Sub Get_Listas()

        Try

            '#GT18102022_1150: agregue tran en varias de las consultas, porque se subconsultaba a otros métodos
            pListBEPropietarioSeleccion = clsLnPropietario_bodega.Get_All_By_IdBodega_For_Seleccion(AP.IdBodega)
            pListBETipoRSeleccion = clsLnTipo_rotacion.Get_All_For_Selection()
            pListBEIndiceRSeleccion = clsLnIndice_rotacion.Get_All_For_Seleccion()
            pListBEEstado = clsLnProducto_estado.Get_All_For_Seleccion()
            pListBETipo = clsLnProducto_tipo.Get_All_For_Seleccion()
            pListBEPres = clsLnProducto_presentacion.Get_All_For_Seleccion_By_IdBodega(AP.IdBodega)

        Catch ex As Exception

            XtraMessageBox.Show(ex.Message,
            Text,
            MessageBoxButtons.OK,
            MessageBoxIcon.Error)

            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)

        End Try

    End Sub

    Public Sub Actualizar_Grid_Propietarios()
        Try
            DgridPropietario.DataSource = pListBEPropietarioSeleccion
            If grdvPropietario.Columns.Count > 0 Then
                grdvPropietario.LayoutChanged()
            End If

            Dim item As GridColumnSummaryItem = New GridColumnSummaryItem(SummaryItemType.Count, "Seleccion", "Propietarios={0}")

            If grdvPropietario.Columns("Seleccion").Summary.Count = 0 Then
                grdvPropietario.Columns("Seleccion").Summary.Add(item)
            End If
        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
            Throw ex
        End Try
    End Sub

    Private Sub Actualizar_Grid_TipoRotacion()
        Try
            DgridTipoRotacion.DataSource = pListBETipoRSeleccion
            If grdvTipoRotacion.Columns.Count > 0 Then
                grdvTipoRotacion.LayoutChanged()
            End If

            Dim item As GridColumnSummaryItem = New GridColumnSummaryItem(SummaryItemType.Count, "IdTipoRotacion", "TiposRotación={0}")

            If grdvTipoRotacion.Columns("IdTipoRotacion").Summary.Count = 0 Then
                grdvTipoRotacion.Columns("IdTipoRotacion").Summary.Add(item)
            End If
        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
            Throw ex
        End Try
    End Sub

    Private Sub Actualizar_Grid_IndiceRotacion()
        Try
            DgridIndiceRotacion.DataSource = pListBEIndiceRSeleccion
            If grdvIndiceRotacion.Columns.Count > 0 Then
                grdvIndiceRotacion.LayoutChanged()
            End If

            Dim item As GridColumnSummaryItem = New GridColumnSummaryItem(SummaryItemType.Count, "IdIndiceRotacion", "IndicesRotación={0}")

            If grdvIndiceRotacion.Columns("IdIndiceRotacion").Summary.Count = 0 Then
                grdvIndiceRotacion.Columns("IdIndiceRotacion").Summary.Add(item)
            End If
        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
            Throw ex
        End Try
    End Sub

    Private Sub Actualizar_Grid_Estado()

        Try

            If pListBEEstado IsNot Nothing AndAlso pListBEEstado.Count > 0 Then

                Dim DT As New DataTable("EstadoProducto")
                DT.Columns.Add(("Seleccion"), GetType(Boolean))
                DT.Columns.Add(("idEstado"), GetType(Integer))
                DT.Columns.Add(("Nombre"), GetType(String))
                DT.Columns.Add(("Propietario"), GetType(String))

                For Each Obj As clsBeProducto_estado_selection In pListBEEstado
                    DT.Rows.Add(Obj.Seleccion, Obj.idEstado, Obj.Nombre, Obj.Propietario.Nombre_comercial)
                Next

                DgridEstadoProducto.DataSource = DT

            End If

            If grdvEstadoProducto.Columns.Count > 0 Then
                grdvEstadoProducto.LayoutChanged()
            End If

            Dim item As GridColumnSummaryItem = New GridColumnSummaryItem(SummaryItemType.Count, "Seleccion", "Estados={0}")

            If grdvEstadoProducto.Columns("Seleccion").Summary.Count = 0 Then
                grdvEstadoProducto.Columns("Seleccion").Summary.Add(item)
            End If

        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
            Throw ex
        End Try

    End Sub

    Private Sub Actualizar_Grid_Tipo()

        Try

            DgridTipoProducto.DataSource = pListBETipo

            If grdvTipoProducto.Columns.Count > 0 Then
                grdvTipoProducto.LayoutChanged()
            End If

            Dim item As GridColumnSummaryItem = New GridColumnSummaryItem(SummaryItemType.Count, "Seleccion", "Tipos={0}")

            If grdvTipoProducto.Columns("Seleccion").Summary.Count = 0 Then
                grdvTipoProducto.Columns("Seleccion").Summary.Add(item)
            End If

        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
            Throw ex
        End Try

    End Sub

    Private Sub Actualizar_Grid_Pres()

        Try

            DgridPresentation.DataSource = pListBEPres

            If grdvPresentation.Columns.Count > 0 Then
                grdvPresentation.LayoutChanged()
            End If

            Dim item As GridColumnSummaryItem = New GridColumnSummaryItem(SummaryItemType.Count, "Seleccion", "Presentaciones={0}")

            If grdvPresentation.Columns("Seleccion").Summary.Count = 0 Then
                grdvPresentation.Columns("Seleccion").Summary.Add(item)
            End If

        Catch ex As Exception
            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)
            Throw ex
        End Try

    End Sub

    Private Sub frmTipoTarima_Load(sender As Object, e As EventArgs) Handles MyBase.Load


        Try

            Top = 50
            Left = (Screen.PrimaryScreen.WorkingArea.Width - Width) / 2
            grdvPropietario.FocusRectStyle = Views.Grid.DrawFocusRectStyle.RowFullFocus
            grdvTipoRotacion.FocusRectStyle = Views.Grid.DrawFocusRectStyle.RowFullFocus
            grdvIndiceRotacion.FocusRectStyle = Views.Grid.DrawFocusRectStyle.RowFullFocus
            grdvEstadoProducto.FocusRectStyle = Views.Grid.DrawFocusRectStyle.RowFullFocus
            grdvTipoProducto.FocusRectStyle = Views.Grid.DrawFocusRectStyle.RowFullFocus
            grdvPresentation.FocusRectStyle = Views.Grid.DrawFocusRectStyle.RowFullFocus

            SplashScreenManager.ShowForm(Me, GetType(WaitForm), True, True, False)
            SplashScreenManager.Default.SetWaitFormCaption("Cargando...")

            Get_Listas()

            SplashScreenManager.ShowForm(Me, GetType(WaitForm), True, True, False)
            SplashScreenManager.Default.SetWaitFormCaption("Actualizando Grid...")

            Actualizar_Grid_Propietarios()
            Actualizar_Grid_TipoRotacion()
            Actualizar_Grid_IndiceRotacion()
            Actualizar_Grid_Estado()
            Actualizar_Grid_Tipo()
            Actualizar_Grid_Pres()

            pListObjT = clsBD.GetLongitudByTabla("regla_ubic_enc")

            Select Case Modo

                Case TipoTrans.Nuevo

                    pBeReglaUbicEnc = New clsBeRegla_ubic_enc With
                        {.IdReglaUbicacionEnc = clsLnRegla_ubic_enc.MaxID(),
                        .IsNew = True}

                    lblCodigo.Text = pBeReglaUbicEnc.IdReglaUbicacionEnc

                    User_agrTextEdit.Text = AP.UsuarioAp.IdUsuario
                    Fec_agrDateEdit.Text = Now
                    User_modTextEdit.Text = AP.UsuarioAp.IdUsuario
                    Fec_modDateEdit.Text = Now

                    If OpcionesMenu IsNot Nothing Then
                        mnuGuardar.Enabled = OpcionesMenu.Modificar
                    End If

                    mnuActualizar.Enabled = False
                    mnuEliminar.Enabled = False

                    RibbonPageGroup4.Visible = False

                Case TipoTrans.Editar

                    clsLnRegla_ubic_enc.GetSingleWithDetails(pBeReglaUbicEnc)

                    Listar_Detalle()

                    lblCodigo.Text = pBeReglaUbicEnc.IdReglaUbicacionEnc
                    txtNombre.Text = pBeReglaUbicEnc.Nombre
                    chkActivo.Checked = pBeReglaUbicEnc.Activo

                    User_agrTextEdit.Text = pBeReglaUbicEnc.User_agr
                    Fec_agrDateEdit.Text = pBeReglaUbicEnc.Fec_agr
                    User_modTextEdit.Text = pBeReglaUbicEnc.User_mod
                    Fec_modDateEdit.Text = pBeReglaUbicEnc.Fec_mod

                    mnuGuardar.Enabled = False

                    If OpcionesMenu IsNot Nothing Then
                        mnuActualizar.Enabled = OpcionesMenu.Modificar
                        mnuEliminar.Enabled = OpcionesMenu.Eliminar
                    End If

                    RibbonPageGroup4.Visible = True

            End Select

            Dim ritem As RepositoryItemCheckEdit = TryCast(grdvPropietario.Columns("Seleccion").RealColumnEdit, RepositoryItemCheckEdit)
            AddHandler ritem.CheckedChanged, AddressOf ritemPropietario_CheckedChanged

            Dim ritem1 As RepositoryItemCheckEdit = TryCast(grdvTipoRotacion.Columns("Activo").RealColumnEdit, RepositoryItemCheckEdit)
            AddHandler ritem1.CheckedChanged, AddressOf ritemTipoR_CheckedChanged

            Dim ritem2 As RepositoryItemCheckEdit = TryCast(grdvIndiceRotacion.Columns("Activo").RealColumnEdit, RepositoryItemCheckEdit)
            AddHandler ritem2.CheckedChanged, AddressOf ritemIndiceR_CheckedChanged

            Dim ritem3 As RepositoryItemCheckEdit = TryCast(grdvEstadoProducto.Columns("Seleccion").RealColumnEdit, RepositoryItemCheckEdit)
            AddHandler ritem3.CheckedChanged, AddressOf ritemEstadoProd_CheckedChanged

            Dim ritem4 As RepositoryItemCheckEdit = TryCast(grdvTipoProducto.Columns("Seleccion").RealColumnEdit, RepositoryItemCheckEdit)
            AddHandler ritem4.CheckedChanged, AddressOf ritemTipoProd_CheckedChanged

            Dim ritem5 As RepositoryItemCheckEdit = TryCast(grdvPresentation.Columns("Seleccion").RealColumnEdit, RepositoryItemCheckEdit)
            AddHandler ritem5.CheckedChanged, AddressOf ritemPresentation_CheckedChanged

            Focus()
            txtNombre.Focus()

        Catch ex As Exception

            SplashScreenManager.CloseForm(False)

            XtraMessageBox.Show(ex.Message,
            Text,
            MessageBoxButtons.OK,
            MessageBoxIcon.Error)

            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)

        Finally
            SplashScreenManager.CloseForm(False)
        End Try

    End Sub

    Private Sub ritemPropietario_CheckedChanged(sender As Object, e As EventArgs)

        Try

            Dim ritem As CheckEdit = TryCast(sender, CheckEdit)

            If Not ritem Is Nothing Then

                Dim Dr As New clsBePropietarioBodegaSeleccion
                Dr = grdvPropietario.GetFocusedRow
                Dim lIndex As Integer = -1

                lIndex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop.FindIndex(Function(b) b.IdPropietarioBodega = Dr.IdPropietarioBodega)

                If lIndex > -1 Then

                    If ritem.Checked Then
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop(lIndex).Activo = True
                    Else
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop(lIndex).Activo = False
                    End If

                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop(lIndex).User_mod = AP.UsuarioAp.IdUsuario
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop(lIndex).Fec_mod = Now

                Else

                    Dim Obj As New clsBeRegla_ubic_det_prop() With {.IdPropietarioBodega = Dr.IdPropietarioBodega, .User_agr = AP.UsuarioAp.IdUsuario, .Fec_agr = Now, .User_mod = AP.UsuarioAp.IdUsuario, .Fec_mod = Now, .Activo = True, .IsNew = True}
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop.Add(Obj)

                End If

            End If

        Catch ex As Exception

            XtraMessageBox.Show(ex.Message,
            Text,
            MessageBoxButtons.OK,
            MessageBoxIcon.Error)

            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)

        End Try

    End Sub

    Private Sub ritemTipoR_CheckedChanged(sender As Object, e As EventArgs)

        Try

            Dim ritem As CheckEdit = TryCast(sender, CheckEdit)

            If Not ritem Is Nothing Then

                Dim Dr As New clsBeTipo_rotacion
                Dr = grdvTipoRotacion.GetFocusedRow
                Dim lIndex As Integer = -1

                lIndex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr.FindIndex(Function(b) b.IdTipoRotacion = Dr.IdTipoRotacion)

                If lIndex > -1 Then

                    If ritem.Checked Then
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr(lIndex).Activo = True
                    Else
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr(lIndex).Activo = False
                    End If

                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr(lIndex).User_mod = AP.UsuarioAp.IdUsuario
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr(lIndex).Fec_mod = Now

                Else

                    Dim Obj As New clsBeRegla_ubic_det_tr() With {.IdTipoRotacion = Dr.IdTipoRotacion, .User_agr = AP.UsuarioAp.IdUsuario, .Fec_agr = Now, .User_mod = AP.UsuarioAp.IdUsuario, .Fec_mod = Now, .Activo = True, .IsNew = True}
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr.Add(Obj)

                End If

            End If

        Catch ex As Exception

            XtraMessageBox.Show(ex.Message,
            Text,
            MessageBoxButtons.OK,
            MessageBoxIcon.Error)

            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)

        End Try

    End Sub

    Private Sub ritemIndiceR_CheckedChanged(sender As Object, e As EventArgs)

        Try

            Dim ritem As CheckEdit = TryCast(sender, CheckEdit)

            If Not ritem Is Nothing Then

                Dim Dr As New clsBeIndice_rotacion
                Dr = grdvIndiceRotacion.GetFocusedRow
                Dim lIndex As Integer = -1

                lIndex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir.FindIndex(Function(b) b.IdIndiceRotacion = Dr.IdIndiceRotacion)

                If lIndex > -1 Then

                    If ritem.Checked Then
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir(lIndex).Activo = True
                    Else
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir(lIndex).Activo = False
                    End If

                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir(lIndex).User_mod = AP.UsuarioAp.IdUsuario
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir(lIndex).Fec_mod = Now

                Else

                    Dim Obj As New clsBeRegla_ubic_det_ir() With {.IdIndiceRotacion = Dr.IdIndiceRotacion, .User_agr = AP.UsuarioAp.IdUsuario, .Fec_agr = Now, .User_mod = AP.UsuarioAp.IdUsuario, .Fec_mod = Now, .Activo = True, .IsNew = True}
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir.Add(Obj)

                End If

            End If

        Catch ex As Exception

            XtraMessageBox.Show(ex.Message,
            Text,
            MessageBoxButtons.OK,
            MessageBoxIcon.Error)

            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)

        End Try

    End Sub

    Private Sub ritemEstadoProd_CheckedChanged(sender As Object, e As EventArgs)

        Try

            Dim ritem As CheckEdit = TryCast(sender, CheckEdit)

            If Not ritem Is Nothing Then

                'Dim Dr As New clsBeProducto_estado_selection '#EJC 20180603 Modificó la declaración del DR
                Dim Dr As DataRowView
                Dr = grdvEstadoProducto.GetFocusedRow

                Dim IdEstado As Integer = Integer.Parse(Dr.Item("idEstado"))

                Dim lIndex As Integer = -1

                lIndex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe.FindIndex(Function(b) b.IdEstado = IdEstado)

                If lIndex > -1 Then

                    If ritem.Checked Then
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe(lIndex).Activo = True
                    Else
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe(lIndex).Activo = False
                    End If

                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe(lIndex).User_mod = AP.UsuarioAp.IdUsuario
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe(lIndex).Fec_mod = Now

                Else

                    Dim Obj As New clsBeRegla_ubic_det_pe() With {.IdEstado = IdEstado, .User_agr = AP.UsuarioAp.IdUsuario, .Fec_agr = Now, .User_mod = AP.UsuarioAp.IdUsuario, .Fec_mod = Now, .Activo = True, .IsNew = True}
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe.Add(Obj)

                End If

            End If

        Catch ex As Exception

            XtraMessageBox.Show(ex.Message,
            Text,
            MessageBoxButtons.OK,
            MessageBoxIcon.Error)

            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)

        End Try

    End Sub

    Private Sub ritemTipoProd_CheckedChanged(sender As Object, e As EventArgs)

        Try

            Dim ritem As CheckEdit = TryCast(sender, CheckEdit)

            If Not ritem Is Nothing Then

                Dim Dr As New clsBeProducto_tipo_seleccion
                Dr = grdvTipoProducto.GetFocusedRow
                Dim lIndex As Integer = -1

                lIndex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp.FindIndex(Function(b) b.IdTipoProducto = Dr.idTipoProducto)

                If lIndex > -1 Then

                    If ritem.Checked Then
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp(lIndex).Activo = True
                    Else
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp(lIndex).Activo = False
                    End If

                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp(lIndex).User_mod = AP.UsuarioAp.IdUsuario
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp(lIndex).Fec_mod = Now

                Else

                    Dim Obj As New clsBeRegla_ubic_det_tp() With {.IdTipoProducto = Dr.idTipoProducto, .User_agr = AP.UsuarioAp.IdUsuario, .Fec_agr = Now, .User_mod = AP.UsuarioAp.IdUsuario, .Fec_mod = Now, .Activo = True, .IsNew = True}
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp.Add(Obj)

                End If

            End If

        Catch ex As Exception

            XtraMessageBox.Show(ex.Message,
            Text,
            MessageBoxButtons.OK,
            MessageBoxIcon.Error)

            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)

        End Try
    End Sub

    Private Sub ritemPresentation_CheckedChanged(sender As Object, e As EventArgs)

        Try

            Dim ritem As CheckEdit = TryCast(sender, CheckEdit)

            If Not ritem Is Nothing Then

                Dim Dr As New clsBeProducto_presentacion_sel
                Dr = grdvPresentation.GetFocusedRow
                Dim lIndex As Integer = -1

                lIndex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp.FindIndex(Function(b) b.IdPresentacion = Dr.idPresentacion)

                If lIndex > -1 Then

                    If ritem.Checked Then
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp(lIndex).Activo = True
                    Else
                        pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp(lIndex).Activo = False
                    End If

                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp(lIndex).User_mod = AP.UsuarioAp.IdUsuario
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp(lIndex).Fec_mod = Now

                Else

                    Dim Obj As New clsBeRegla_ubic_det_pp() With {.IdPresentacion = Dr.idPresentacion, .User_agr = AP.UsuarioAp.IdUsuario, .Fec_agr = Now, .User_mod = AP.UsuarioAp.IdUsuario, .Fec_mod = Now, .Activo = True, .IsNew = True}
                    pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp.Add(Obj)

                End If

            End If

        Catch ex As Exception

            XtraMessageBox.Show(ex.Message,
            Text,
            MessageBoxButtons.OK,
            MessageBoxIcon.Error)

            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)

        End Try
    End Sub

    Private Function Datos_Correctos()

        Datos_Correctos = False

        Try

            If String.IsNullOrEmpty(txtNombre.Text.Trim()) Then
                XtraMessageBox.Show("Ingrese Nombre.", Text, MessageBoxButtons.OK, MessageBoxIcon.Information)
                txtNombre.Focus()
            ElseIf txtNombre.Text.Count > pListObjT.Find(Function(b) b.NombreCampo.ToUpper = "NOMBRE").Longitud Then
                XtraMessageBox.Show(String.Format("El Nombre debe de tener como máximo {0} carácteres.", pListObjT.Find(Function(ByVal b) b.NombreCampo.ToUpper = "NOMBRE").Longitud), Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
                txtNombre.Focus()
            Else
                Datos_Correctos = True
            End If

        Catch ex As Exception

            XtraMessageBox.Show(ex.Message,
            Text,
            MessageBoxButtons.OK,
            MessageBoxIcon.Error)

            Dim vMsgError As String = ex.Message
            clsLnLog_error_wms.Agregar_Error(vMsgError)

        End Try

    End Function

    Private Sub Listar_Detalle()

        Try

            Listar_Propietarios()
            Listar_TipoRotacion()
            Listar_IndiceRotacion()
            Listar_Estado()
            Listar_Tipo()
            Listar_Presentacion()

        Catch ex As Exception
            XtraMessageBox.Show(ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
        End Try

    End Sub

    Private Sub Listar_Propietarios()

        Try

            If Not pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop Is Nothing Then

                Dim lindex As Integer = -1
                Dim lindex1 As Integer = -1

                For Each Prop As clsBeRegla_ubic_det_prop In pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop

                    lindex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop.FindIndex(Function(x) x.IdPropietarioBodega = Prop.IdPropietarioBodega)
                    lindex1 = pListBEPropietarioSeleccion.FindIndex(Function(x) x.IdPropietarioBodega = Prop.IdPropietarioBodega)

                    If lindex <> -1 AndAlso lindex1 <> -1 Then
                        pListBEPropietarioSeleccion(lindex1).Seleccion = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Prop(lindex).Activo
                    End If

                Next

                Actualizar_Grid_Propietarios()

            End If

        Catch ex As Exception
            XtraMessageBox.Show(ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
        End Try


    End Sub

    Private Sub Listar_TipoRotacion()

        Try

            If Not pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr Is Nothing Then

                Dim lindex As Integer = -1
                Dim lindex1 As Integer = -1

                For Each Tr As clsBeRegla_ubic_det_tr In pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr

                    lindex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr.FindIndex(Function(x) x.IdTipoRotacion = Tr.IdTipoRotacion)
                    lindex1 = pListBETipoRSeleccion.FindIndex(Function(x) x.IdTipoRotacion = Tr.IdTipoRotacion)

                    If lindex <> -1 AndAlso lindex1 <> -1 Then
                        pListBETipoRSeleccion(lindex1).Activo = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Tr(lindex).Activo
                    End If

                Next

                Actualizar_Grid_TipoRotacion()

            End If

        Catch ex As Exception
            XtraMessageBox.Show(ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
        End Try


    End Sub

    Private Sub Listar_IndiceRotacion()

        Try

            If Not pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir Is Nothing Then

                Dim lindex As Integer = -1
                Dim lindex1 As Integer = -1

                For Each Ir As clsBeRegla_ubic_det_ir In pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir

                    lindex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir.FindIndex(Function(x) x.IdIndiceRotacion = Ir.IdIndiceRotacion)
                    lindex1 = pListBEIndiceRSeleccion.FindIndex(Function(x) x.IdIndiceRotacion = Ir.IdIndiceRotacion)

                    If lindex <> -1 AndAlso lindex1 <> -1 Then
                        pListBEIndiceRSeleccion(lindex1).Activo = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Ir(lindex).Activo
                    End If

                Next

                Actualizar_Grid_IndiceRotacion()

            End If

        Catch ex As Exception
            XtraMessageBox.Show(ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
        End Try


    End Sub

    Private Sub Listar_Estado()

        Try

            If Not pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe Is Nothing Then

                Dim lindex As Integer = -1
                Dim lindex1 As Integer = -1

                For Each pe As clsBeRegla_ubic_det_pe In pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe

                    lindex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe.FindIndex(Function(x) x.IdEstado = pe.IdEstado)
                    lindex1 = pListBEEstado.FindIndex(Function(x) x.idEstado = pe.IdEstado)

                    If lindex <> -1 AndAlso lindex1 <> -1 Then
                        pListBEEstado(lindex1).Seleccion = pBeReglaUbicEnc.listDetRegla_Ubic_Det_Pe(lindex).Activo
                    End If

                Next

                Actualizar_Grid_Estado()

            End If

        Catch ex As Exception
            XtraMessageBox.Show(ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
        End Try


    End Sub

    Private Sub Listar_Tipo()

        Try

            If Not pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp Is Nothing Then

                Dim lindex As Integer = -1
                Dim lindex1 As Integer = -1

                For Each tp As clsBeRegla_ubic_det_tp In pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp

                    lindex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp.FindIndex(Function(x) x.IdTipoProducto = tp.IdTipoProducto)
                    lindex1 = pListBETipo.FindIndex(Function(x) x.idTipoProducto = tp.IdTipoProducto)

                    If lindex <> -1 AndAlso lindex1 <> -1 Then
                        pListBETipo(lindex1).Seleccion = pBeReglaUbicEnc.listDetRegla_Ubic_Det_tp(lindex).Activo
                    End If

                Next

                Actualizar_Grid_Tipo()

            End If

        Catch ex As Exception
            XtraMessageBox.Show(ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
        End Try

    End Sub

    Private Sub Listar_Presentacion()

        Try

            If Not pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp Is Nothing Then

                Dim lindex As Integer = -1
                Dim lindex1 As Integer = -1

                For Each pp As clsBeRegla_ubic_det_pp In pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp

                    lindex = pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp.FindIndex(Function(x) x.IdPresentacion = pp.IdPresentacion)
                    lindex1 = pListBEPres.FindIndex(Function(x) x.idPresentacion = pp.IdPresentacion)

                    If lindex <> -1 AndAlso lindex1 <> -1 Then
                        pListBEPres(lindex1).Seleccion = pBeReglaUbicEnc.listDetRegla_Ubic_Det_pp(lindex).Activo
                    End If

                Next

                Actualizar_Grid_Pres()

            End If

        Catch ex As Exception
            XtraMessageBox.Show(ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)
        End Try

    End Sub

    Private Function Guardar_Regla() As Boolean

        Guardar_Regla = False

        Try

            If pBeReglaUbicEnc.IsNew Then

                pBeReglaUbicEnc.IdReglaUbicacionEnc = clsLnRegla_ubic_enc.MaxID
                pBeReglaUbicEnc.IdEmpresa = AP.IdEmpresa
                pBeReglaUbicEnc.IdBodega = AP.IdBodega

            End If

            pBeReglaUbicEnc.User_agr = AP.UsuarioAp.IdUsuario
            pBeReglaUbicEnc.Fec_agr = Now
            pBeReglaUbicEnc.User_mod = AP.UsuarioAp.IdUsuario
            pBeReglaUbicEnc.Fec_mod = Now

            pBeReglaUbicEnc.Nombre = txtNombre.Text.Trim()
            pBeReglaUbicEnc.Activo = chkActivo.Checked

            Guardar_Regla = clsLnRegla_ubic_enc.Guardar_Regla(pBeReglaUbicEnc)

        Catch ex As Exception
            XtraMessageBox.Show(String.Format("{0} {1}", MethodBase.GetCurrentMethod.Name(), ex.Message), Text, MessageBoxButtons.OK, MessageBoxIcon.Error)
        End Try

    End Function

    Private Sub mnuGuardar_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuGuardar.ItemClick

        Try

            mnuGuardar.Enabled = False

            If Datos_Correctos() Then
                If XtraMessageBox.Show("¿Guardar?", Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then
                    If Guardar_Regla() Then
                        XtraMessageBox.Show("Se guardó el registro", Text, MessageBoxButtons.OK, MessageBoxIcon.Information)
                        If InvokeListarReglas IsNot Nothing Then
                            InvokeListarReglas.Invoke()
                        End If
                        RibbonPageGroup4.Visible = True
                    End If
                End If
            End If

        Catch ex As Exception
            mnuGuardar.Enabled = True
            XtraMessageBox.Show(String.Format("{0} {1}", MethodBase.GetCurrentMethod.Name(), ex.Message), Text, MessageBoxButtons.OK, MessageBoxIcon.Error)
        End Try

    End Sub

    Private Sub mnuActualizar_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuActualizar.ItemClick

        mnuActualizar.Enabled = False

        Try

            If Datos_Correctos() Then
                If XtraMessageBox.Show("¿Guardar registro?", Text, MessageBoxButtons.YesNo, MessageBoxIcon.Question) = DialogResult.Yes Then
                    If Guardar_Regla() Then
                        Botones_Modo_Edicion()
                        XtraMessageBox.Show("Se actualizó el registro", Text, MessageBoxButtons.OK, MessageBoxIcon.Information)
                        If InvokeListarReglas IsNot Nothing Then
                            InvokeListarReglas.Invoke()
                        End If
                        PanelControl1.Visible = True
                        Close()
                    End If
                End If
            End If

        Catch ex As Exception
            XtraMessageBox.Show(String.Format("{0} {1}", MethodBase.GetCurrentMethod.Name(), ex.Message), Text, MessageBoxButtons.OK, MessageBoxIcon.Error)
        End Try

        mnuActualizar.Enabled = True
    End Sub

    Private Sub Botones_Modo_Edicion()

        mnuGuardar.Enabled = False
        mnuActualizar.Enabled = True
        mnuEliminar.Enabled = True

        RibbonPageGroup4.Visible = True

    End Sub
    Private Sub mnuUbic_ItemClick(sender As Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles mnuUbic.ItemClick
        Dim Regla As New frmAsociacionReglaUbicacion() With {.Modo = frmAsociacionReglaUbicacion.pModo.Lista, .IdReglaUbicacionEnc = pBeReglaUbicEnc.IdReglaUbicacionEnc}
        Regla.ShowDialog()
        Regla.Dispose()
    End Sub

    Private Sub frmReglaUbic_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode = Keys.Escape Then Close()
    End Sub

    Private Sub XtraTabControl1_SelectedPageChanged(sender As Object, e As DevExpress.XtraTab.TabPageChangedEventArgs) Handles XtraTabControl1.SelectedPageChanged

        Try

            Dim selectedTab As DevExpress.XtraTab.XtraTabPage = e.Page
            Dim lPropietarios As New List(Of Integer)
            Dim lTiposRotacion As New List(Of Integer)
            Dim lIndicesRotacion As New List(Of Integer)

            If selectedTab Is tabTiposProductos Then

                ' Iterar sobre las filas del GridView
                For i As Integer = 0 To grdvPropietario.RowCount - 1
                    ' Verificar si la fila está seleccionada (checkbox marcado)
                    Dim isChecked As Boolean = Convert.ToBoolean(grdvPropietario.GetRowCellValue(i, "Seleccion"))

                    If isChecked Then
                        ' Obtener el valor del IdPropietario
                        Dim idPropietario As Integer = Convert.ToInt32(grdvPropietario.GetRowCellValue(i, "IdPropietarioBodega"))
                        ' Agregar a la lista
                        lPropietarios.Add(idPropietario)
                    End If
                Next

                ' Iterar sobre las filas del GridView
                For i As Integer = 0 To grdvTipoRotacion.RowCount - 1
                    ' Verificar si la fila está seleccionada (checkbox marcado)
                    Dim isChecked As Boolean = Convert.ToBoolean(grdvTipoRotacion.GetRowCellValue(i, "Activo"))

                    If isChecked Then
                        ' Obtener el valor del IdPropietario
                        Dim IdTipoRotacion As Integer = Convert.ToInt32(grdvTipoRotacion.GetRowCellValue(i, "IdTipoRotacion"))
                        ' Agregar a la lista
                        lTiposRotacion.Add(IdTipoRotacion)
                    End If
                Next

                ' Iterar sobre las filas del GridView
                For i As Integer = 0 To grdvIndiceRotacion.RowCount - 1
                    ' Verificar si la fila está seleccionada (checkbox marcado)
                    Dim isChecked As Boolean = Convert.ToBoolean(grdvIndiceRotacion.GetRowCellValue(i, "Activo"))

                    If isChecked Then
                        ' Obtener el valor del IdPropietario
                        Dim IdIndiceRotacion As Integer = Convert.ToInt32(grdvIndiceRotacion.GetRowCellValue(i, "IdIndiceRotacion"))
                        ' Agregar a la lista
                        lIndicesRotacion.Add(IdIndiceRotacion)
                    End If
                Next

                pListBETipo = clsLnProducto_tipo.Get_All_For_Seleccion_By_Filtros(lPropietarios, lTiposRotacion, lIndicesRotacion)

                Listar_Tipo()

            End If

        Catch ex As Exception
            XtraMessageBox.Show(String.Format("{0} {1}", MethodBase.GetCurrentMethod.Name(), ex.Message), Text, MessageBoxButtons.OK, MessageBoxIcon.Error)
        End Try

    End Sub

End Class