DEBUG = OFF

#PROGRAX-CEALSAQA
SERVIDOR_BD_WMS = PROGRAX\SQLEXPRESS
NOMBRE_BD_WMS = IMS4MB_IDEALSA_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS =sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 4
SERVIDOR_SQL_ERP =192.168.0.63
NOMBRE_BD_ERP = aritecdb
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
TIMEOUT_BD_ERP = 0
#FIN

#A - CEALSAQA
SERVIDOR_BD_WMS = ADM-HV-SRVTEST\SQLEXPRESS
NOMBRE_BD_WMS = IMS4MB_CEALSA_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS =Admin1965!
SEGURIDAD_INTEGRADA_WMS = NO
IDCONFIGURACION = 4
SERVIDOR_SQL_ERP =192.168.0.63
NOMBRE_BD_ERP = aritecdb
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
TIMEOUT_BD_ERP = 0
#FIN
