DEBUG = ON

#LA_CUMBRE_VPN_QA
SERVIDOR_BD_WMS =LAPTOP-5GDJFUCN\PROGRAX
NOMBRE_BD_WMS = TOMWMS_LA_CUMBRE_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =10.10.1.12:40000
SERVER_BD_SAP = 10.10.1.12
SAP_COMPANY_DB = SBO_COLONIAL_PRUEBAS
SAP_USR = manager
SAP_USR_PW = Sap2024*
SAP_DB_USR = Consultor
SAP_DB_PW = Consultor#23_
SAP_DB_VERSION = 2019
TIMEOUT = 0
IDCONFIGURACION = 1
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
URL_ENTRADA_AJUSTE_POST = http://10.10.1.12:8088/api/TOMWMS/Entrada
URL_SALIDA_AJUSTE_POST =http://10.10.1.12:8088/api/TOMWMS/Salida
#FIN