DEBUG = OFF


#Becofarma23_QA2
SERVIDOR_BD_WMS = DELL
NOMBRE_BD_WMS = IMS4MB_BECOFARMA_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =192.168.0.129:40000
SERVER_BD_SAP = 192.168.0.129
SAP_COMPANY_DB = TEST_BECO_LOTES
SAP_USR = Sap01
SAP_USR_PW = Welcome02
SAP_DB_PW = Becofarma23
SAP_DB_USR = sa
TIMEOUT = 0
FORMATO_DESPACHO = 1
#FIN


#BECOFARMA_QA
SERVIDOR = SRV-BODEGA\SQLEXPRESS
BD = IMS4MB_MOVESA
USUARIO = sap
CLAVE =12345678
SEGURIDAD_INTEGRADA = NO
LICENSESERVER_SAP_BO =192.168.0.129:30000
SERVER_BD_SAP = 192.168.0.129 -- SQLSRV
SAP_COMPANY_DB = TEST_BECO_LOTES
SAP_USR = Sap01
SAP_USR_PW = Welcome02
SAP_DB_USR = sa
SAP_DB_PW = Becofarma23
TIMEOUT = 0
IDCONFIGURACION = 2
#FIN
