'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSPedidoTransferencia
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Pedidos_Transferencia_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia")>  _
    Partial Public Class Pedidos_Transferencia_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ReadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadByRecIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsUpdatedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRecIdFromKeyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Delete_TransferLinesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.TOMWMS.My.MySettings.Default.DynamicsNavInterface_WsPedidoTransferencia_Pedidos_Transferencia_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ReadCompleted As ReadCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadByRecIdCompleted As ReadByRecIdCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadMultipleCompleted As ReadMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event IsUpdatedCompleted As IsUpdatedCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRecIdFromKeyCompleted As GetRecIdFromKeyCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateCompleted As CreateCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateMultipleCompleted As CreateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCompleted As UpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateMultipleCompleted As UpdateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCompleted As DeleteCompletedEventHandler
        
        '''<remarks/>
        Public Event Delete_TransferLinesCompleted As Delete_TransferLinesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal No As String) As <System.Xml.Serialization.XmlElementAttribute("Pedidos_Transferencia")> Pedidos_Transferencia
            Dim results() As Object = Me.Invoke("Read", New Object() {No})
            Return CType(results(0),Pedidos_Transferencia)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal No As String)
            Me.ReadAsync(No, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal No As String, ByVal userState As Object)
            If (Me.ReadOperationCompleted Is Nothing) Then
                Me.ReadOperationCompleted = AddressOf Me.OnReadOperationCompleted
            End If
            Me.InvokeAsync("Read", New Object() {No}, Me.ReadOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadCompleted(Me, New ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("Pedidos_Transferencia")> Pedidos_Transferencia
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),Pedidos_Transferencia)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String)
            Me.ReadByRecIdAsync(recId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String, ByVal userState As Object)
            If (Me.ReadByRecIdOperationCompleted Is Nothing) Then
                Me.ReadByRecIdOperationCompleted = AddressOf Me.OnReadByRecIdOperationCompleted
            End If
            Me.InvokeAsync("ReadByRecId", New Object() {recId}, Me.ReadByRecIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadByRecIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadByRecIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadByRecIdCompleted(Me, New ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As Pedidos_Transferencia_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> Pedidos_Transferencia()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),Pedidos_Transferencia())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As Pedidos_Transferencia_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer)
            Me.ReadMultipleAsync(filter, bookmarkKey, setSize, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As Pedidos_Transferencia_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal userState As Object)
            If (Me.ReadMultipleOperationCompleted Is Nothing) Then
                Me.ReadMultipleOperationCompleted = AddressOf Me.OnReadMultipleOperationCompleted
            End If
            Me.InvokeAsync("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, Me.ReadMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadMultipleCompleted(Me, New ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String)
            Me.IsUpdatedAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.IsUpdatedOperationCompleted Is Nothing) Then
                Me.IsUpdatedOperationCompleted = AddressOf Me.OnIsUpdatedOperationCompleted
            End If
            Me.InvokeAsync("IsUpdated", New Object() {Key}, Me.IsUpdatedOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsUpdatedOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsUpdatedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsUpdatedCompleted(Me, New IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String)
            Me.GetRecIdFromKeyAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.GetRecIdFromKeyOperationCompleted Is Nothing) Then
                Me.GetRecIdFromKeyOperationCompleted = AddressOf Me.OnGetRecIdFromKeyOperationCompleted
            End If
            Me.InvokeAsync("GetRecIdFromKey", New Object() {Key}, Me.GetRecIdFromKeyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRecIdFromKeyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRecIdFromKeyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRecIdFromKeyCompleted(Me, New GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:Create", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="Create_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Create(ByRef Pedidos_Transferencia As Pedidos_Transferencia)
            Dim results() As Object = Me.Invoke("Create", New Object() {Pedidos_Transferencia})
            Pedidos_Transferencia = CType(results(0),Pedidos_Transferencia)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal Pedidos_Transferencia As Pedidos_Transferencia)
            Me.CreateAsync(Pedidos_Transferencia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal Pedidos_Transferencia As Pedidos_Transferencia, ByVal userState As Object)
            If (Me.CreateOperationCompleted Is Nothing) Then
                Me.CreateOperationCompleted = AddressOf Me.OnCreateOperationCompleted
            End If
            Me.InvokeAsync("Create", New Object() {Pedidos_Transferencia}, Me.CreateOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCompleted(Me, New CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:CreateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="CreateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef Pedidos_Transferencia_List() As Pedidos_Transferencia)
            Dim results() As Object = Me.Invoke("CreateMultiple", New Object() {Pedidos_Transferencia_List})
            Pedidos_Transferencia_List = CType(results(0),Pedidos_Transferencia())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal Pedidos_Transferencia_List() As Pedidos_Transferencia)
            Me.CreateMultipleAsync(Pedidos_Transferencia_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal Pedidos_Transferencia_List() As Pedidos_Transferencia, ByVal userState As Object)
            If (Me.CreateMultipleOperationCompleted Is Nothing) Then
                Me.CreateMultipleOperationCompleted = AddressOf Me.OnCreateMultipleOperationCompleted
            End If
            Me.InvokeAsync("CreateMultiple", New Object() {Pedidos_Transferencia_List}, Me.CreateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateMultipleCompleted(Me, New CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef Pedidos_Transferencia As Pedidos_Transferencia)
            Dim results() As Object = Me.Invoke("Update", New Object() {Pedidos_Transferencia})
            Pedidos_Transferencia = CType(results(0),Pedidos_Transferencia)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal Pedidos_Transferencia As Pedidos_Transferencia)
            Me.UpdateAsync(Pedidos_Transferencia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal Pedidos_Transferencia As Pedidos_Transferencia, ByVal userState As Object)
            If (Me.UpdateOperationCompleted Is Nothing) Then
                Me.UpdateOperationCompleted = AddressOf Me.OnUpdateOperationCompleted
            End If
            Me.InvokeAsync("Update", New Object() {Pedidos_Transferencia}, Me.UpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCompleted(Me, New UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef Pedidos_Transferencia_List() As Pedidos_Transferencia)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {Pedidos_Transferencia_List})
            Pedidos_Transferencia_List = CType(results(0),Pedidos_Transferencia())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal Pedidos_Transferencia_List() As Pedidos_Transferencia)
            Me.UpdateMultipleAsync(Pedidos_Transferencia_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal Pedidos_Transferencia_List() As Pedidos_Transferencia, ByVal userState As Object)
            If (Me.UpdateMultipleOperationCompleted Is Nothing) Then
                Me.UpdateMultipleOperationCompleted = AddressOf Me.OnUpdateMultipleOperationCompleted
            End If
            Me.InvokeAsync("UpdateMultiple", New Object() {Pedidos_Transferencia_List}, Me.UpdateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateMultipleCompleted(Me, New UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:Delete", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="Delete_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String)
            Me.DeleteAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.DeleteOperationCompleted Is Nothing) Then
                Me.DeleteOperationCompleted = AddressOf Me.OnDeleteOperationCompleted
            End If
            Me.InvokeAsync("Delete", New Object() {Key}, Me.DeleteOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCompleted(Me, New DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/pedidos_transferencia:Delete_TransferLines", RequestNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", ResponseElementName:="Delete_TransferLines_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete_TransferLines(ByVal TransferLines_Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_TransferLines_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete_TransferLines", New Object() {TransferLines_Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Delete_TransferLinesAsync(ByVal TransferLines_Key As String)
            Me.Delete_TransferLinesAsync(TransferLines_Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Delete_TransferLinesAsync(ByVal TransferLines_Key As String, ByVal userState As Object)
            If (Me.Delete_TransferLinesOperationCompleted Is Nothing) Then
                Me.Delete_TransferLinesOperationCompleted = AddressOf Me.OnDelete_TransferLinesOperationCompleted
            End If
            Me.InvokeAsync("Delete_TransferLines", New Object() {TransferLines_Key}, Me.Delete_TransferLinesOperationCompleted, userState)
        End Sub
        
        Private Sub OnDelete_TransferLinesOperationCompleted(ByVal arg As Object)
            If (Not (Me.Delete_TransferLinesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Delete_TransferLinesCompleted(Me, New Delete_TransferLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia")>  _
    Partial Public Class Pedidos_Transferencia
        
        Private keyField As String
        
        Private noField As String
        
        Private transfer_from_CodeField As String
        
        Private transfer_to_CodeField As String
        
        Private in_Transit_CodeField As String
        
        Private posting_DateField As Date
        
        Private posting_DateFieldSpecified As Boolean
        
        Private shortcut_Dimension_1_CodeField As String
        
        Private shortcut_Dimension_2_CodeField As String
        
        Private assigned_User_IDField As String
        
        Private statusField As Status
        
        Private statusFieldSpecified As Boolean
        
        Private external_Document_NoField As String
        
        Private shipment_DateField As Date
        
        Private shipment_DateFieldSpecified As Boolean
        
        Private outbound_Whse_Handling_TimeField As String
        
        Private shipment_Method_CodeField As String
        
        Private shipping_Agent_CodeField As String
        
        Private shipping_Agent_Service_CodeField As String
        
        Private shipping_TimeField As String
        
        Private shipping_AdviceField As Shipping_Advice
        
        Private shipping_AdviceFieldSpecified As Boolean
        
        Private last_Shipment_NoField As String
        
        Private receipt_DateField As Date
        
        Private receipt_DateFieldSpecified As Boolean
        
        Private transfer_from_NameField As String
        
        Private transfer_from_Name_2Field As String
        
        Private transfer_from_AddressField As String
        
        Private transfer_from_Address_2Field As String
        
        Private transfer_from_CityField As String
        
        Private transfer_from_CountyField As String
        
        Private transfer_from_Post_CodeField As String
        
        Private transfer_from_ContactField As String
        
        Private transfer_to_NameField As String
        
        Private transfer_to_Name_2Field As String
        
        Private transfer_to_AddressField As String
        
        Private transfer_to_Address_2Field As String
        
        Private transfer_to_CityField As String
        
        Private transfer_to_CountyField As String
        
        Private transfer_to_Post_CodeField As String
        
        Private transfer_to_ContactField As String
        
        Private inbound_Whse_Handling_TimeField As String
        
        Private transaction_TypeField As String
        
        Private transaction_SpecificationField As String
        
        Private transport_MethodField As String
        
        Private areaField As String
        
        Private entry_Exit_PointField As String
        
        Private transferLinesField() As Transfer_Order_Line
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property No() As String
            Get
                Return Me.noField
            End Get
            Set
                Me.noField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_Code() As String
            Get
                Return Me.transfer_from_CodeField
            End Get
            Set
                Me.transfer_from_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_to_Code() As String
            Get
                Return Me.transfer_to_CodeField
            End Get
            Set
                Me.transfer_to_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property In_Transit_Code() As String
            Get
                Return Me.in_Transit_CodeField
            End Get
            Set
                Me.in_Transit_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Posting_Date() As Date
            Get
                Return Me.posting_DateField
            End Get
            Set
                Me.posting_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Posting_DateSpecified() As Boolean
            Get
                Return Me.posting_DateFieldSpecified
            End Get
            Set
                Me.posting_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_1_Code() As String
            Get
                Return Me.shortcut_Dimension_1_CodeField
            End Get
            Set
                Me.shortcut_Dimension_1_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_2_Code() As String
            Get
                Return Me.shortcut_Dimension_2_CodeField
            End Get
            Set
                Me.shortcut_Dimension_2_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Assigned_User_ID() As String
            Get
                Return Me.assigned_User_IDField
            End Get
            Set
                Me.assigned_User_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StatusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property External_Document_No() As String
            Get
                Return Me.external_Document_NoField
            End Get
            Set
                Me.external_Document_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Shipment_Date() As Date
            Get
                Return Me.shipment_DateField
            End Get
            Set
                Me.shipment_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Shipment_DateSpecified() As Boolean
            Get
                Return Me.shipment_DateFieldSpecified
            End Get
            Set
                Me.shipment_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Outbound_Whse_Handling_Time() As String
            Get
                Return Me.outbound_Whse_Handling_TimeField
            End Get
            Set
                Me.outbound_Whse_Handling_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shipment_Method_Code() As String
            Get
                Return Me.shipment_Method_CodeField
            End Get
            Set
                Me.shipment_Method_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shipping_Agent_Code() As String
            Get
                Return Me.shipping_Agent_CodeField
            End Get
            Set
                Me.shipping_Agent_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shipping_Agent_Service_Code() As String
            Get
                Return Me.shipping_Agent_Service_CodeField
            End Get
            Set
                Me.shipping_Agent_Service_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shipping_Time() As String
            Get
                Return Me.shipping_TimeField
            End Get
            Set
                Me.shipping_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shipping_Advice() As Shipping_Advice
            Get
                Return Me.shipping_AdviceField
            End Get
            Set
                Me.shipping_AdviceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Shipping_AdviceSpecified() As Boolean
            Get
                Return Me.shipping_AdviceFieldSpecified
            End Get
            Set
                Me.shipping_AdviceFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Last_Shipment_No() As String
            Get
                Return Me.last_Shipment_NoField
            End Get
            Set
                Me.last_Shipment_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Receipt_Date() As Date
            Get
                Return Me.receipt_DateField
            End Get
            Set
                Me.receipt_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Receipt_DateSpecified() As Boolean
            Get
                Return Me.receipt_DateFieldSpecified
            End Get
            Set
                Me.receipt_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_Name() As String
            Get
                Return Me.transfer_from_NameField
            End Get
            Set
                Me.transfer_from_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_Name_2() As String
            Get
                Return Me.transfer_from_Name_2Field
            End Get
            Set
                Me.transfer_from_Name_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_Address() As String
            Get
                Return Me.transfer_from_AddressField
            End Get
            Set
                Me.transfer_from_AddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_Address_2() As String
            Get
                Return Me.transfer_from_Address_2Field
            End Get
            Set
                Me.transfer_from_Address_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_City() As String
            Get
                Return Me.transfer_from_CityField
            End Get
            Set
                Me.transfer_from_CityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_County() As String
            Get
                Return Me.transfer_from_CountyField
            End Get
            Set
                Me.transfer_from_CountyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_Post_Code() As String
            Get
                Return Me.transfer_from_Post_CodeField
            End Get
            Set
                Me.transfer_from_Post_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_Contact() As String
            Get
                Return Me.transfer_from_ContactField
            End Get
            Set
                Me.transfer_from_ContactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_to_Name() As String
            Get
                Return Me.transfer_to_NameField
            End Get
            Set
                Me.transfer_to_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_to_Name_2() As String
            Get
                Return Me.transfer_to_Name_2Field
            End Get
            Set
                Me.transfer_to_Name_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_to_Address() As String
            Get
                Return Me.transfer_to_AddressField
            End Get
            Set
                Me.transfer_to_AddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_to_Address_2() As String
            Get
                Return Me.transfer_to_Address_2Field
            End Get
            Set
                Me.transfer_to_Address_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_to_City() As String
            Get
                Return Me.transfer_to_CityField
            End Get
            Set
                Me.transfer_to_CityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_to_County() As String
            Get
                Return Me.transfer_to_CountyField
            End Get
            Set
                Me.transfer_to_CountyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_to_Post_Code() As String
            Get
                Return Me.transfer_to_Post_CodeField
            End Get
            Set
                Me.transfer_to_Post_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_to_Contact() As String
            Get
                Return Me.transfer_to_ContactField
            End Get
            Set
                Me.transfer_to_ContactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Inbound_Whse_Handling_Time() As String
            Get
                Return Me.inbound_Whse_Handling_TimeField
            End Get
            Set
                Me.inbound_Whse_Handling_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaction_Type() As String
            Get
                Return Me.transaction_TypeField
            End Get
            Set
                Me.transaction_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaction_Specification() As String
            Get
                Return Me.transaction_SpecificationField
            End Get
            Set
                Me.transaction_SpecificationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transport_Method() As String
            Get
                Return Me.transport_MethodField
            End Get
            Set
                Me.transport_MethodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Area() As String
            Get
                Return Me.areaField
            End Get
            Set
                Me.areaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Entry_Exit_Point() As String
            Get
                Return Me.entry_Exit_PointField
            End Get
            Set
                Me.entry_Exit_PointField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property TransferLines() As Transfer_Order_Line()
            Get
                Return Me.transferLinesField
            End Get
            Set
                Me.transferLinesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia")>  _
    Public Enum Status
        
        '''<remarks/>
        Open
        
        '''<remarks/>
        Released
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia")>  _
    Public Enum Shipping_Advice
        
        '''<remarks/>
        [Partial]
        
        '''<remarks/>
        Complete
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia")>  _
    Partial Public Class Transfer_Order_Line
        
        Private keyField As String
        
        Private item_NoField As String
        
        Private variant_CodeField As String
        
        Private planning_FlexibilityField As Planning_Flexibility
        
        Private planning_FlexibilityFieldSpecified As Boolean
        
        Private descriptionField As String
        
        Private transfer_from_Bin_CodeField As String
        
        Private transfer_To_Bin_CodeField As String
        
        Private quantityField As Decimal
        
        Private quantityFieldSpecified As Boolean
        
        Private reserved_Quantity_InbndField As Decimal
        
        Private reserved_Quantity_InbndFieldSpecified As Boolean
        
        Private reserved_Quantity_ShippedField As Decimal
        
        Private reserved_Quantity_ShippedFieldSpecified As Boolean
        
        Private reserved_Quantity_OutbndField As Decimal
        
        Private reserved_Quantity_OutbndFieldSpecified As Boolean
        
        Private unit_of_Measure_CodeField As String
        
        Private unit_of_MeasureField As String
        
        Private qty_to_ShipField As Decimal
        
        Private qty_to_ShipFieldSpecified As Boolean
        
        Private quantity_ShippedField As Decimal
        
        Private quantity_ShippedFieldSpecified As Boolean
        
        Private qty_to_ReceiveField As Decimal
        
        Private qty_to_ReceiveFieldSpecified As Boolean
        
        Private quantity_ReceivedField As Decimal
        
        Private quantity_ReceivedFieldSpecified As Boolean
        
        Private shipment_DateField As Date
        
        Private shipment_DateFieldSpecified As Boolean
        
        Private receipt_DateField As Date
        
        Private receipt_DateFieldSpecified As Boolean
        
        Private shipping_Agent_CodeField As String
        
        Private shipping_Agent_Service_CodeField As String
        
        Private shipping_TimeField As String
        
        Private outbound_Whse_Handling_TimeField As String
        
        Private inbound_Whse_Handling_TimeField As String
        
        Private line_NoField As Integer
        
        Private line_NoFieldSpecified As Boolean
        
        Private appl_to_Item_EntryField As Integer
        
        Private appl_to_Item_EntryFieldSpecified As Boolean
        
        Private shortcut_Dimension_1_CodeField As String
        
        Private shortcut_Dimension_2_CodeField As String
        
        Private shortcutDimCode3Field As String
        
        Private shortcutDimCode4Field As String
        
        Private shortcutDimCode5Field As String
        
        Private shortcutDimCode6Field As String
        
        Private shortcutDimCode7Field As String
        
        Private shortcutDimCode8Field As String
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Item_No() As String
            Get
                Return Me.item_NoField
            End Get
            Set
                Me.item_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Variant_Code() As String
            Get
                Return Me.variant_CodeField
            End Get
            Set
                Me.variant_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Planning_Flexibility() As Planning_Flexibility
            Get
                Return Me.planning_FlexibilityField
            End Get
            Set
                Me.planning_FlexibilityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Planning_FlexibilitySpecified() As Boolean
            Get
                Return Me.planning_FlexibilityFieldSpecified
            End Get
            Set
                Me.planning_FlexibilityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_from_Bin_Code() As String
            Get
                Return Me.transfer_from_Bin_CodeField
            End Get
            Set
                Me.transfer_from_Bin_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transfer_To_Bin_Code() As String
            Get
                Return Me.transfer_To_Bin_CodeField
            End Get
            Set
                Me.transfer_To_Bin_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity() As Decimal
            Get
                Return Me.quantityField
            End Get
            Set
                Me.quantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property QuantitySpecified() As Boolean
            Get
                Return Me.quantityFieldSpecified
            End Get
            Set
                Me.quantityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reserved_Quantity_Inbnd() As Decimal
            Get
                Return Me.reserved_Quantity_InbndField
            End Get
            Set
                Me.reserved_Quantity_InbndField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Reserved_Quantity_InbndSpecified() As Boolean
            Get
                Return Me.reserved_Quantity_InbndFieldSpecified
            End Get
            Set
                Me.reserved_Quantity_InbndFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reserved_Quantity_Shipped() As Decimal
            Get
                Return Me.reserved_Quantity_ShippedField
            End Get
            Set
                Me.reserved_Quantity_ShippedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Reserved_Quantity_ShippedSpecified() As Boolean
            Get
                Return Me.reserved_Quantity_ShippedFieldSpecified
            End Get
            Set
                Me.reserved_Quantity_ShippedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reserved_Quantity_Outbnd() As Decimal
            Get
                Return Me.reserved_Quantity_OutbndField
            End Get
            Set
                Me.reserved_Quantity_OutbndField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Reserved_Quantity_OutbndSpecified() As Boolean
            Get
                Return Me.reserved_Quantity_OutbndFieldSpecified
            End Get
            Set
                Me.reserved_Quantity_OutbndFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Unit_of_Measure_Code() As String
            Get
                Return Me.unit_of_Measure_CodeField
            End Get
            Set
                Me.unit_of_Measure_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Unit_of_Measure() As String
            Get
                Return Me.unit_of_MeasureField
            End Get
            Set
                Me.unit_of_MeasureField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Qty_to_Ship() As Decimal
            Get
                Return Me.qty_to_ShipField
            End Get
            Set
                Me.qty_to_ShipField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Qty_to_ShipSpecified() As Boolean
            Get
                Return Me.qty_to_ShipFieldSpecified
            End Get
            Set
                Me.qty_to_ShipFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity_Shipped() As Decimal
            Get
                Return Me.quantity_ShippedField
            End Get
            Set
                Me.quantity_ShippedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Quantity_ShippedSpecified() As Boolean
            Get
                Return Me.quantity_ShippedFieldSpecified
            End Get
            Set
                Me.quantity_ShippedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Qty_to_Receive() As Decimal
            Get
                Return Me.qty_to_ReceiveField
            End Get
            Set
                Me.qty_to_ReceiveField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Qty_to_ReceiveSpecified() As Boolean
            Get
                Return Me.qty_to_ReceiveFieldSpecified
            End Get
            Set
                Me.qty_to_ReceiveFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Quantity_Received() As Decimal
            Get
                Return Me.quantity_ReceivedField
            End Get
            Set
                Me.quantity_ReceivedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Quantity_ReceivedSpecified() As Boolean
            Get
                Return Me.quantity_ReceivedFieldSpecified
            End Get
            Set
                Me.quantity_ReceivedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Shipment_Date() As Date
            Get
                Return Me.shipment_DateField
            End Get
            Set
                Me.shipment_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Shipment_DateSpecified() As Boolean
            Get
                Return Me.shipment_DateFieldSpecified
            End Get
            Set
                Me.shipment_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Receipt_Date() As Date
            Get
                Return Me.receipt_DateField
            End Get
            Set
                Me.receipt_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Receipt_DateSpecified() As Boolean
            Get
                Return Me.receipt_DateFieldSpecified
            End Get
            Set
                Me.receipt_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shipping_Agent_Code() As String
            Get
                Return Me.shipping_Agent_CodeField
            End Get
            Set
                Me.shipping_Agent_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shipping_Agent_Service_Code() As String
            Get
                Return Me.shipping_Agent_Service_CodeField
            End Get
            Set
                Me.shipping_Agent_Service_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shipping_Time() As String
            Get
                Return Me.shipping_TimeField
            End Get
            Set
                Me.shipping_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Outbound_Whse_Handling_Time() As String
            Get
                Return Me.outbound_Whse_Handling_TimeField
            End Get
            Set
                Me.outbound_Whse_Handling_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Inbound_Whse_Handling_Time() As String
            Get
                Return Me.inbound_Whse_Handling_TimeField
            End Get
            Set
                Me.inbound_Whse_Handling_TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Line_No() As Integer
            Get
                Return Me.line_NoField
            End Get
            Set
                Me.line_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Line_NoSpecified() As Boolean
            Get
                Return Me.line_NoFieldSpecified
            End Get
            Set
                Me.line_NoFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Appl_to_Item_Entry() As Integer
            Get
                Return Me.appl_to_Item_EntryField
            End Get
            Set
                Me.appl_to_Item_EntryField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Appl_to_Item_EntrySpecified() As Boolean
            Get
                Return Me.appl_to_Item_EntryFieldSpecified
            End Get
            Set
                Me.appl_to_Item_EntryFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_1_Code() As String
            Get
                Return Me.shortcut_Dimension_1_CodeField
            End Get
            Set
                Me.shortcut_Dimension_1_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_2_Code() As String
            Get
                Return Me.shortcut_Dimension_2_CodeField
            End Get
            Set
                Me.shortcut_Dimension_2_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[3]")>  _
        Public Property ShortcutDimCode3() As String
            Get
                Return Me.shortcutDimCode3Field
            End Get
            Set
                Me.shortcutDimCode3Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[4]")>  _
        Public Property ShortcutDimCode4() As String
            Get
                Return Me.shortcutDimCode4Field
            End Get
            Set
                Me.shortcutDimCode4Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[5]")>  _
        Public Property ShortcutDimCode5() As String
            Get
                Return Me.shortcutDimCode5Field
            End Get
            Set
                Me.shortcutDimCode5Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[6]")>  _
        Public Property ShortcutDimCode6() As String
            Get
                Return Me.shortcutDimCode6Field
            End Get
            Set
                Me.shortcutDimCode6Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[7]")>  _
        Public Property ShortcutDimCode7() As String
            Get
                Return Me.shortcutDimCode7Field
            End Get
            Set
                Me.shortcutDimCode7Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[8]")>  _
        Public Property ShortcutDimCode8() As String
            Get
                Return Me.shortcutDimCode8Field
            End Get
            Set
                Me.shortcutDimCode8Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia")>  _
    Public Enum Planning_Flexibility
        
        '''<remarks/>
        Unlimited
        
        '''<remarks/>
        None
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia")>  _
    Partial Public Class Pedidos_Transferencia_Filter
        
        Private fieldField As Pedidos_Transferencia_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As Pedidos_Transferencia_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/pedidos_transferencia")>  _
    Public Enum Pedidos_Transferencia_Fields
        
        '''<remarks/>
        No
        
        '''<remarks/>
        Transfer_from_Code
        
        '''<remarks/>
        Transfer_to_Code
        
        '''<remarks/>
        In_Transit_Code
        
        '''<remarks/>
        Posting_Date
        
        '''<remarks/>
        Shortcut_Dimension_1_Code
        
        '''<remarks/>
        Shortcut_Dimension_2_Code
        
        '''<remarks/>
        Assigned_User_ID
        
        '''<remarks/>
        Status
        
        '''<remarks/>
        External_Document_No
        
        '''<remarks/>
        Shipment_Date
        
        '''<remarks/>
        Outbound_Whse_Handling_Time
        
        '''<remarks/>
        Shipment_Method_Code
        
        '''<remarks/>
        Shipping_Agent_Code
        
        '''<remarks/>
        Shipping_Agent_Service_Code
        
        '''<remarks/>
        Shipping_Time
        
        '''<remarks/>
        Shipping_Advice
        
        '''<remarks/>
        Last_Shipment_No
        
        '''<remarks/>
        Receipt_Date
        
        '''<remarks/>
        Transfer_from_Name
        
        '''<remarks/>
        Transfer_from_Name_2
        
        '''<remarks/>
        Transfer_from_Address
        
        '''<remarks/>
        Transfer_from_Address_2
        
        '''<remarks/>
        Transfer_from_City
        
        '''<remarks/>
        Transfer_from_County
        
        '''<remarks/>
        Transfer_from_Post_Code
        
        '''<remarks/>
        Transfer_from_Contact
        
        '''<remarks/>
        Transfer_to_Name
        
        '''<remarks/>
        Transfer_to_Name_2
        
        '''<remarks/>
        Transfer_to_Address
        
        '''<remarks/>
        Transfer_to_Address_2
        
        '''<remarks/>
        Transfer_to_City
        
        '''<remarks/>
        Transfer_to_County
        
        '''<remarks/>
        Transfer_to_Post_Code
        
        '''<remarks/>
        Transfer_to_Contact
        
        '''<remarks/>
        Inbound_Whse_Handling_Time
        
        '''<remarks/>
        Transaction_Type
        
        '''<remarks/>
        Transaction_Specification
        
        '''<remarks/>
        Transport_Method
        
        '''<remarks/>
        Area
        
        '''<remarks/>
        Entry_Exit_Point
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReadCompletedEventHandler(ByVal sender As Object, ByVal e As ReadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Pedidos_Transferencia
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Pedidos_Transferencia)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReadByRecIdCompletedEventHandler(ByVal sender As Object, ByVal e As ReadByRecIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadByRecIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Pedidos_Transferencia
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Pedidos_Transferencia)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ReadMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As ReadMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Pedidos_Transferencia()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Pedidos_Transferencia())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub IsUpdatedCompletedEventHandler(ByVal sender As Object, ByVal e As IsUpdatedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsUpdatedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetRecIdFromKeyCompletedEventHandler(ByVal sender As Object, ByVal e As GetRecIdFromKeyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRecIdFromKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CreateCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Pedidos_Transferencia() As Pedidos_Transferencia
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Pedidos_Transferencia)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub CreateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As CreateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Pedidos_Transferencia_List() As Pedidos_Transferencia()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Pedidos_Transferencia())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub UpdateCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Pedidos_Transferencia() As Pedidos_Transferencia
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Pedidos_Transferencia)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub UpdateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Pedidos_Transferencia_List() As Pedidos_Transferencia()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Pedidos_Transferencia())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub DeleteCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Delete_TransferLinesCompletedEventHandler(ByVal sender As Object, ByVal e As Delete_TransferLinesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Delete_TransferLinesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
