'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WSRegistraRecepcionCompra
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Registra_Recepcion_Compra_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/codeunit/Registra_Recepcion_Compra")>  _
    Partial Public Class Registra_Recepcion_Compra
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RegistrarRecCompraOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.TOMWMS.My.MySettings.Default.DynamicsNavInterface_WSRegistraRecepcionCompra_Registra_Recepcion_Compra
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RegistrarRecCompraCompleted As RegistrarRecCompraCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/Registra_Recepcion_Compra:RegistrarRecCom"& _ 
            "pra", RequestNamespace:="urn:microsoft-dynamics-schemas/codeunit/Registra_Recepcion_Compra", ResponseElementName:="RegistrarRecCompra_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/codeunit/Registra_Recepcion_Compra", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub RegistrarRecCompra(ByVal numero_Documento As String)
            Me.Invoke("RegistrarRecCompra", New Object() {numero_Documento})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarRecCompraAsync(ByVal numero_Documento As String)
            Me.RegistrarRecCompraAsync(numero_Documento, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RegistrarRecCompraAsync(ByVal numero_Documento As String, ByVal userState As Object)
            If (Me.RegistrarRecCompraOperationCompleted Is Nothing) Then
                Me.RegistrarRecCompraOperationCompleted = AddressOf Me.OnRegistrarRecCompraOperationCompleted
            End If
            Me.InvokeAsync("RegistrarRecCompra", New Object() {numero_Documento}, Me.RegistrarRecCompraOperationCompleted, userState)
        End Sub
        
        Private Sub OnRegistrarRecCompraOperationCompleted(ByVal arg As Object)
            If (Not (Me.RegistrarRecCompraCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RegistrarRecCompraCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub RegistrarRecCompraCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
