#PRODUCCION
SERVIDOR = 52.32.154.252
BD = ims4mb_qa
USUARIO = ejc
CLAVE =Admin1965
SEGURIDAD_INTEGRADA = NO
IPWCF=http://ec2-52-32-154-252.us-west-2.compute.amazonaws.com/TOMWCF/
TIMEOUT = 30
#FIN

#DEV
SERVIDOR = PROGRAN
BD = ims4mb_qa
USUARIO = sa
CLAVE =sysadm
SEGURIDAD_INTEGRADA = NO
IPWCF=http://localhost:4180/
TIMEOUT = 0
#FIN

#QAS
SERVIDOR = 52.32.154.252
BD = ims4mb_qa
USUARIO = ejc
CLAVE =Admin1965
SEGURIDAD_INTEGRADA = NO
IPWCF=http://ec2-52-32-154-252.us-west-2.compute.amazonaws.com/TOMWCF/
#FIN

#PRODUCCION
SERVIDOR = 52.32.154.252
BD = ims4mb_qa
USUARIO = ejc
CLAVE =Admin1965
SEGURIDAD_INTEGRADA = NO
IPWCF=http://localhost:4180/
TIMEOUT = 30
#FIN