DEBUG = OFF

#1-QUICKTAG-DEMO
NOMBRE_BD_WMS = TOMWMS_QUICKTAG
SERVIDOR_BD_WMS = DESARROLLO-PC8
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
FORMATO_DESPACHO = 3
TIMEOUT_BD_ERP = 0
ID_EMPRESA_TMS = 1
ID_EMPRESA_QUICKTAG= 1
ID_STANDALONE = 1
#FIN


