#CLC_GEN-PRD
SERVIDOR_BD_WMS = GSCLCWMS\SQLEXPRESS
NOMBRE_BD_WMS = IMS4MB_CLC_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
TIMEOUT = 0
FORMATO_RECEPCION= 1
#FIN


#\\gsclcwms\WMS_GEN_101122\
