DEBUG = ON

#2 - SERVER_PRUEBAS
SERVIDOR_BD_WMS = DTSOLUTIONS\SQLEXPRESS
NOMBRE_BD_WMS = TOMWMS_MAMPA_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbTest
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
TIMEOUT_BD_ERP = 120
FORMATO_DESPACHO= 5
TIMEOUT = 150
LICENSESERVER_SAP_BO =
SERVER_BD_SAP = 10.238.26.76:30015
SAP_COMPANY_DB = SBO_AGORA_GSBK
SAP_USR = DTSolutions
SAP_USR_PW = DtS202502
SAP_DB_USR = DEVDTS
SAP_DB_PW = Solutions2025.
SAP_BD_VERSION = 
IDCONFIGURACION = 2
FORMATO_RECEPCION=2
HANA_SL=https://10.238.26.78:50000/b1s/v1/
HANA_SL_USR=DevAccess
HANA_SL_PWD=d3V_205!W4
#FIN


#1-SERVER_PRODUCCION
SERVIDOR_BD_WMS = 192.168.1.60
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAP
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdb
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
FORMATO_RECEPCION= 1
FORMATO_DESPACHO = 3
TIMEOUT_BD_ERP = 120
TIMEOUT = 150
#FIN

