#BECOFARMA_QAS
SERVIDOR_BD_WMS = LAPTOP-5GDJFUCN\PROGRAX
NOMBRE_BD_WMS = TOMWMS_LA_CUMBRE_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =10.238.113.195:40000
SERVER_BD_SAP = 10.238.113.194
SAP_COMPANY_DB = TEST_BACH_19012024
SAP_USR = manager
SAP_USR_PW = 2023CC
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
SAP_DB_VERSION = 2019
TIMEOUT = 0
IDCONFIGURACION = 1
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
#FIN

#PROGRAX-IMS4MB_INELAC_PRD
SERVIDOR_BD_WMS = LAPTOP-5GDJFUCN\PROGRAX
NOMBRE_BD_WMS = IMS4MB_INELAC_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
#FIN

#MERCOPAN-PRD
SERVIDOR_BD_WMS = PROGRAX\SQLEXPRESS
NOMBRE_BD_WMS = IMS4MB_BYB_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
TIMEOUT = 0
#FIN

#MERCOSAL-QA
SERVIDOR_BD_WMS = 192.168.126.80
NOMBRE_BD_WMS = IMS4MB_MERCOSAL_QA
USUARIO_BD_WMS = mi3_user
CLAVE_BD_WMS = mi3_user2018
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
#FIN


#BECOFARMA_QA
SERVIDOR_BD_WMS = DESARROLLO8-PC\SQL2019
NOMBRE_BD_WMS = IMS4MB_BECOFARMA_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =192.168.0.129:40000
SERVER_BD_SAP = sqlsrv
SAP_COMPANY_DB = TEST_BECO_LOTES
SAP_USR = manager
SAP_USR_PW = 2023CC
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
TIMEOUT = 0
IDCONFIGURACION = 1
#FIN

#CLC_FIS-PRD
SERVIDOR_BD_WMS = DESARROLLO8-PC\SQL2019
NOMBRE_BD_WMS = IMS4MB_CLC_REV
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
FORMATO_INGRESO_FISCAL =1
TIMEOUT_BD_ERP = 120
#FIN

#1-SERVER_PRODUCCION
SERVIDOR_BD_WMS = DESARROLLO8-PC\SQL2019
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAP
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbpruebas
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
FORMATO_DESPACHO = 3
TIMEOUT_BD_ERP = 120
#FIN


#BECOFARMA_QAS
SERVIDOR_BD_WMS = 10.238.113.198
NOMBRE_BD_WMS = IMS4MB_BECOFARMA_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =10.238.113.195:40000
SERVER_BD_SAP = 10.238.113.194
SAP_COMPANY_DB = TEST_BACH_19012024
SAP_USR = manager
SAP_USR_PW = 2023CC
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
SAP_DB_VERSION = 2019
TIMEOUT = 0
IDCONFIGURACION = 1
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
#FIN