DEBUG = ON

#MAMPA_QA_HANNA
SERVIDOR_BD_WMS = WMSDEV
NOMBRE_BD_WMS = TOMWMS_MAMPA_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =
SERVER_BD_SAP = 10.238.26.76:30015
SAP_COMPANY_DB = SBO_AGORA_GSBK
SAP_USR = DTSolutions
SAP_USR_PW = DtS202502
SAP_DB_USR = DEVDTS
SAP_DB_PW = Solutions2025.
SAP_BD_VERSION = 
TIMEOUT = 0
IDCONFIGURACION = 1
#FIN
