DEBUG = OFF

#CKFK-QA
SERVIDOR_BD_WMS = PROGRA14\SQL2022
NOMBRE_BD_WMS = TOMWMS_LA_CUMBRE_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
TIMEOUT = 0
#FIN

#CKFK-EJR
SERVIDOR_BD_WMS = PROGRA12\SQLEXPRESS01
NOMBRE_BD_WMS = IMS4MB_MERCOSAL_PRD_EJR
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
#FIN

#MERCOPAN-QA
SERVIDOR_BD_WMS = 192.168.126.80
NOMBRE_BD_WMS = IMS4MB_MERCOPAN_QA
USUARIO_BD_WMS = mi3_user
CLAVE_BD_WMS = mi3_user2018
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
#FIN

#SRV_BYB_PRD_WS_REMOTO_IP
SERVIDOR_BD_WMS = PROGRA12\SQLEXPRESS01
NOMBRE_BD_WMS = IMS4MB_BYB_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA_WMS = NO
WSBODEGAS = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Ficha_Bodegas
WSPRODUCTOS = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Productos
WSPROVEEDORES = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Proveedores
WSPEDIDOSCOMPRA = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Pedidos_Compra
WSLOTEPEDIDOCOMPRA =  http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Codeunit/Lote_PedidoCompra
WSCANTPEDIDOCOMPRA  = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Codeunit/CantidadRecibir_PedidoCompra
WSCLIENTES  = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Lista_clientes
WSPEDIDOSTRANSFERENCIA = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Pedidos_Transferencia
WSGRUPOPRODUCTOS = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Grupos_Productos
WSCATEGORIASPRODUCTOS = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Categorias_Productos
WSTABLACONVERSIONES = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Tabla_Conversiones
WSLOTEPEDIDOTRANSF = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Codeunit/Lote_PedidoTransferencia
WSCANTPEDIDOTRANSF = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Codeunit/CantidadEnviar_PedidoTransferencia
WSREGISRECEPCOMPRA=  http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Recepcion_Compra
WSREGISTRANSFENVIO=  http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Transfer_Envio
WSREGISTRANSFRECEP  = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Transfer_Recepcion
WSAJUSTEINV = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Codeunit/Ajustes_Inventario
WSSERIES = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Series
WSLOTESTRANSFREC = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Pagina_lotes
WSPEDIDOSVENTA = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Pedidos 
WSENVIOSALM = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Envio_alm
WSORDENESPRODUCCION = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/OP_Lanzadas
WSDIARIOSALIDA = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Diario_Salida
WSUBICACIONESINTERNTAS = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/U_Internas
WSUBICARALMACEN = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Ubicar_Almacen
WSRECEPCIONESALM = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Recep_Almacen
WSCUWMS = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Codeunit/CUWMS
WSCREAPICKING = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Crea_picking
WSDEVOL = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Devolucion
WSDEVOLVENTA =  http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Devolucion_venta
WSDIARIOALMACEN= http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Diario_Almacen
WSPICKING = http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Picking
WSMOVPRODUCTOS=http://168.194.73.242:1050/DynamicsNAV110/WS/PRALCASA/Page/Mov_Productos
WSTOMHH = http://192.168.0.5/WCFTOM4/TOMHHWS.asmx
TIMEOUT = 0
IDCONFIGURACION = 3
USUARIOWS = wmsbodega1
CLAVEWS = **ProductosbyB.2022++
#FIN

#SRV_BYB_PRD_WS_LOCAL_IP
SERVIDOR_BD_WMS = 122.122.122.80
NOMBRE_BD_WMS = IMS4MB_BYB_PRD
USUARIO_BD_WMS = UsrWMSProd
CLAVE_BD_WMS = U7+NQx*WOV
SEGURIDAD_INTEGRADA_WMS = NO
WSBODEGAS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Ficha_Bodegas
WSPRODUCTOS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Productos
WSPROVEEDORES = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Proveedores
WSPEDIDOSCOMPRA = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Pedidos_Compra
WSLOTEPEDIDOCOMPRA =  http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Lote_PedidoCompra
WSCANTPEDIDOCOMPRA  = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/CantidadRecibir_PedidoCompra
WSCLIENTES  = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Lista_clientes
WSPEDIDOSTRANSFERENCIA = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Pedidos_Transferencia
WSGRUPOPRODUCTOS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Grupos_Productos
WSCATEGORIASPRODUCTOS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Categorias_Productos
WSTABLACONVERSIONES = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Tabla_Conversiones
WSLOTEPEDIDOTRANSF = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Lote_PedidoTransferencia
WSCANTPEDIDOTRANSF = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/CantidadEnviar_PedidoTransferencia
WSREGISRECEPCOMPRA=  http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Recepcion_Compra
WSREGISTRANSFENVIO=  http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Transfer_Envio
WSREGISTRANSFRECEP  = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Transfer_Recepcion
WSAJUSTEINV = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Ajustes_Inventario
WSSERIES = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Series
WSLOTESTRANSFREC = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Pagina_lotes
WSPEDIDOSVENTA = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Pedidos 
WSENVIOSALM = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Envio_alm
WSORDENESPRODUCCION = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/OP_Lanzadas
WSDIARIOSALIDA = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Diario_Salida
WSUBICACIONESINTERNTAS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/U_Internas
WSUBICARALMACEN = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Ubicar_Almacen
WSRECEPCIONESALM = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Recep_Almacen
WSCUWMS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/CUWMS
WSCREAPICKING = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Crea_picking
WSDEVOL = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Devolucion
WSDEVOLVENTA =  http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Devolucion_venta
WSDIARIOALMACEN= http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Diario_Almacen
WSPICKING = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Picking
WSMOVPRODUCTOS=http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Mov_Productos
WSTOMHH = http://10.10.20.181/WCFTOM4/TOMHHWS.asmx
TIMEOUT = 0
IDCONFIGURACION = 3
USUARIOWS = wmsbodega1
CLAVEWS = **ProductosbyB.2022++
#FIN

#SRV_BYB_PRD_WS_LOCAL_IP
SERVIDOR_BD_WMS = 122.122.122.80
NOMBRE_BD_WMS = IMS4MB_BYB_PRD
USUARIO_BD_WMS = UsrWMSProd
CLAVE_BD_WMS = U7+NQx*WOV
SEGURIDAD_INTEGRADA_WMS = NO
WSBODEGAS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Ficha_Bodegas
WSPRODUCTOS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Productos
WSPROVEEDORES = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Proveedores
WSPEDIDOSCOMPRA = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Pedidos_Compra
WSLOTEPEDIDOCOMPRA =  http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Lote_PedidoCompra
WSCANTPEDIDOCOMPRA  = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/CantidadRecibir_PedidoCompra
WSCLIENTES  = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Lista_clientes
WSPEDIDOSTRANSFERENCIA = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Pedidos_Transferencia
WSGRUPOPRODUCTOS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Grupos_Productos
WSCATEGORIASPRODUCTOS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Categorias_Productos
WSTABLACONVERSIONES = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Tabla_Conversiones
WSLOTEPEDIDOTRANSF = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Lote_PedidoTransferencia
WSCANTPEDIDOTRANSF = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/CantidadEnviar_PedidoTransferencia
WSREGISRECEPCOMPRA=  http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Recepcion_Compra
WSREGISTRANSFENVIO=  http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Transfer_Envio
WSREGISTRANSFRECEP  = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Transfer_Recepcion
WSAJUSTEINV = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Ajustes_Inventario
WSSERIES = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Series
WSLOTESTRANSFREC = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Pagina_lotes
WSPEDIDOSVENTA = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Pedidos 
WSENVIOSALM = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Envio_alm
WSORDENESPRODUCCION = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/OP_Lanzadas
WSDIARIOSALIDA = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Diario_Salida
WSUBICACIONESINTERNTAS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/U_Internas
WSUBICARALMACEN = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Ubicar_Almacen
WSRECEPCIONESALM = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Recep_Almacen
WSCUWMS = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/CUWMS
WSCREAPICKING = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Crea_picking
WSDEVOL = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Devolucion
WSDEVOLVENTA =  http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Devolucion_venta
WSDIARIOALMACEN= http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Diario_Almacen
WSPICKING = http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Picking
WSMOVPRODUCTOS=http://122.122.122.97:7047/DynamicsNAV110/WS/PRALCASA/Page/Mov_Productos
WSTOMHH = http://10.10.20.181/WCFTOM4/TOMHHWS.asmx
TIMEOUT = 0
IDCONFIGURACION = 3
USUARIOWS = wmsbodega1
CLAVEWS = **ProductosbyB.2022++
#FIN

#SRV_BYB_QAS_WS_LOCAL_IP
SERVIDOR_BD_WMS = 122.122.122.80
NOMBRE_BD_WMS = IMS4MB_BYB_QA
USUARIO_BD_WMS = UsrWMSProd
CLAVE_BD_WMS = U7+NQx*WOV
SEGURIDAD_INTEGRADA_WMS = NO
WSBODEGAS = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Ficha_Bodegas
WSPRODUCTOS = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Productos
WSPROVEEDORES = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Proveedores
WSPEDIDOSCOMPRA = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Pedidos_Compra
WSLOTEPEDIDOCOMPRA =  http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Lote_PedidoCompra
WSCANTPEDIDOCOMPRA  = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/CantidadRecibir_PedidoCompra
WSCLIENTES  = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Lista_clientes
WSPEDIDOSTRANSFERENCIA = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Pedidos_Transferencia
WSGRUPOPRODUCTOS = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Grupos_Productos
WSCATEGORIASPRODUCTOS = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Categorias_Productos
WSTABLACONVERSIONES = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Tabla_Conversiones
WSLOTEPEDIDOTRANSF = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Lote_PedidoTransferencia
WSCANTPEDIDOTRANSF = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/CantidadEnviar_PedidoTransferencia
WSREGISRECEPCOMPRA=  http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Recepcion_Compra
WSREGISTRANSFENVIO=  http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Transfer_Envio
WSREGISTRANSFRECEP  = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Registra_Transfer_Recepcion
WSAJUSTEINV = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/Ajustes_Inventario
WSSERIES = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Series
WSLOTESTRANSFREC = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Pagina_lotes
WSPEDIDOSVENTA = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Pedidos 
WSENVIOSALM = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Envio_alm
WSORDENESPRODUCCION = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/OP_Lanzadas
WSDIARIOSALIDA = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Diario_Salida
WSUBICACIONESINTERNTAS = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/U_Internas
WSUBICARALMACEN = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Ubicar_Almacen
WSRECEPCIONESALM = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Recep_Almacen
WSCUWMS = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Codeunit/CUWMS
WSCREAPICKING = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Crea_picking
WSDEVOL = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Devolucion
WSDEVOLVENTA =  http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Devolucion_venta
WSDIARIOALMACEN= http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Diario_Almacen
WSPICKING = http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Picking
WSMOVPRODUCTOS=http://122.122.122.21:7047/DynamicsNAV110/WS/PRALCASA/Page/Mov_Productos
WSTOMHH = http://10.10.20.181/WCFTOM4_QA/TOMHHWS.asmx
TIMEOUT = 0
IDCONFIGURACION = 3
USUARIOWS = wmsbodega1
CLAVEWS = **ProductosbyB.2022++
#FIN

#CEALSA
SERVIDOR_BD_WMS = PROGRA12\SQLEXPRESS01
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAP
USUARIO_BD_WMS = sa
CLAVE_BD_WMS =sysadm
SEGURIDAD_INTEGRADA_WMS = NO
#FIN

#MERCOPAN
SERVIDOR_BD_WMS = PROGRA12\SQLEXPRESS01
NOMBRE_BD_WMS = IMS4MB_MERCOPAN_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS =sysadm
SEGURIDAD_INTEGRADA_WMS = NO
#FIN

# CKFK-QA
SERVIDOR_BD_WMS = PROGRA12\SQLEXPRESS01
NOMBRE_BD_WMS = IMS4MB_MERCOPAN_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
#FIN

#1-SERVER_PRODUCCION
SERVIDOR_BD_WMS = 192.168.0.98
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAP
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbpruebas
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
FORMATO_DESPACHO = 3
TIMEOUT_BD_ERP = 0
#FIN

#IODESA-QA
SERVIDOR_BD_WMS = 192.168.126.80
NOMBRE_BD_WMS = IMS4MB_IDEALSA_QA
USUARIO_BD_WMS = mi3_user
CLAVE_BD_WMS = mi3_user2018
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
TIMEOUT = 0
#FIN

#MERCOSAL-QA
SERVIDOR_BD_WMS = 192.168.126.80
NOMBRE_BD_WMS = IMS4MB_MERCOSAL_QA
USUARIO_BD_WMS = mi3_user
CLAVE_BD_WMS = mi3_user2018
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
#FIN

#MERCOPAN-QA
SERVIDOR_BD_WMS = 192.168.126.80
NOMBRE_BD_WMS = IMS4MB_MERCOPAN_QA
USUARIO_BD_WMS = mi3_user
CLAVE_BD_WMS = mi3_user2018
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
TIMEOUT = 0
#FIN

#MERHONSA-QA
SERVIDOR_BD_WMS = 192.168.126.80
NOMBRE_BD_WMS = IMS4MB_MERHONSA_QA
USUARIO_BD_WMS = mi3_user
CLAVE_BD_WMS = mi3_user2018
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
#FIN

#IODESA-PRD
SERVIDOR_BD_WMS = 192.168.125.30
NOMBRE_BD_WMS = IMS4MB_IDEALSA_PRD
USUARIO_BD_WMS = suwms
CLAVE_BD_WMS = WmsId3@ls@2019..
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
TIMEOUT = 0
#FIN

#MERCOSAL-PRD
SERVIDOR_BD_WMS = 192.168.125.30
NOMBRE_BD_WMS = IMS4MB_MERCOSAL_PRD
USUARIO_BD_WMS = suwms
CLAVE_BD_WMS = WmsId3@ls@2019..
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
TIMEOUT = 0
#FIN

#MERCOPAN-PRD
SERVIDOR_BD_WMS = 192.168.125.30
NOMBRE_BD_WMS = IMS4MB_MERCOPAN_PRD
USUARIO_BD_WMS = suwms
CLAVE_BD_WMS = WmsId3@ls@2019..
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
TIMEOUT = 0
#FIN
