#Killios_PRD
SERVIDOR_BD_WMS = 192.168.2.204
NOMBRE_BD_WMS = TOMWMS_KILLIOS_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =192.168.2.211:40000
SERVER_BD_SAP = 192.168.2.211
SAP_COMPANY_DB = SBO_KILIO
SAP_COMPANY_DB2 = SBO_GARESA
SAP_USR = app
SAP_USR_PW = 1Ou9V6es
SAP_DB_USR = sa
SAP_DB_PW = 4P2N9RbzlqD6
SAP_DB_VERSION = 2019
TIMEOUT = 0
FORMATO_DESPACHO = 1
#FIN

#CKFK-QA
SERVIDOR_BD_WMS = PROGRA14\SQL2019
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAP_marzo
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
TIMEOUT = 0
#FIN

#LA_CUMBRE_LOCAL_PRD
SERVIDOR_BD_WMS = DTSOLUTIONS\SQLEXPRESS
NOMBRE_BD_WMS = IMS4MB_BYB_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
TIMEOUT = 0
#FIN
