DEBUG = OFF

#LOCAL_PRD_CLC_MP
SERVIDOR_BD_WMS = 192.168.0.252\SQL2014
NOMBRE_BD_WMS = IMS4MB_CLC_MP
USUARIO_BD_WMS = sa
CLAVE_BD_WMS =Sysadm2018
SEGURIDAD_INTEGRADA = NO
IPWCF=http://localhost:4180/
TIMEOUT = 0
IDCONFIGURACION = -1
#FIN

#LOCAL_PRD_CLC_MP
SERVIDOR = GSCLCWMS\SQL2014
BD = IMS4MB_CLC_MP
USUARIO_BD_WMS = sa
CLAVE =Sysadm2018
SEGURIDAD_INTEGRADA = NO
IPWCF=http://localhost:4180/
TIMEOUT = 0
IDCONFIGURACION = -1
#FIN
