DEBUG = OFF


#SERVER_PRUEBAS
SERVIDOR_BD_WMS = 192.168.1.90
NOMBRE_BD_WMS = IMS4MB_DYD_QAS
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IPWCF=http://localhost:4180/
TIMEOUT = 0
FORMATO_DESPACHO = 4
IDCONFIGURACION = 2
#FIN


#SERVER_PRODUCCION
SERVIDOR_BD_WMS = 192.168.1.90
NOMBRE_BD_WMS = IMS4MB_DYD_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IPWCF=http://localhost:4180/
TIMEOUT = 0
FORMATO_DESPACHO = 4
IDCONFIGURACION = 2
#FIN
