DEBUG = OFF
#IODESA-PRD
SERVIDOR_BD_WMS = 192.168.125.30
NOMBRE_BD_WMS = IMS4MB_IDEALSA_PRD
USUARIO_BD_WMS = suwms
CLAVE_BD_WMS = WmsId3@ls@2019..
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
#FIN

#IODESA-QA
SERVIDOR_BD_WMS = 192.168.126.80
NOMBRE_BD_WMS = IMS4MB_IDEALSA_QA
USUARIO_BD_WMS = mi3_user
CLAVE_BD_WMS = mi3_user2018
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
#FIN



