DEBUG = OFF

#1 - SERVER_PRUEBAS_RFID
SERVIDOR_BD_WMS = 192.168.1.60
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAP
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbTest
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
FORMATO_RECEPCION= 1
FORMATO_DESPACHO = 3
TIMEOUT_BD_ERP = 120
TIMEOUT = 150
#FIN

#2 - SERVER_PRUEBAS
SERVIDOR_BD_WMS = 192.168.1.60
NOMBRE_BD_WMS = TOMWMS_KILLIOS_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbTest
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
FORMATO_RECEPCION= 1
FORMATO_DESPACHO = 3
TIMEOUT_BD_ERP = 120
TIMEOUT = 150
#FIN