#BECOFARMA_QAS
SERVIDOR_BD_WMS = LAPTOP-5GDJFUCN\PROGRAX
NOMBRE_BD_WMS = TOMWMS_LA_CUMBRE_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = Admin1965!*
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =10.238.113.195:40000
SERVER_BD_SAP = 10.238.113.194
SAP_COMPANY_DB = TEST_BACH_19012024
SAP_USR = manager
SAP_USR_PW = 2023CC
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
SAP_DB_VERSION = 2019
TIMEOUT = 0
IDCONFIGURACION = 1
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
#FIN