DEBUG = OFF

#BECOFARMA_QA
SERVIDOR_BD_WMS = DESARROLLO8-PC\SQL2019
NOMBRE_BD_WMS = IMS4MB_BECOFARMA_QA
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
LICENSESERVER_SAP_BO =192.168.0.129:40000
SERVER_BD_SAP = sqlsrv
SAP_COMPANY_DB = TEST_BECO_LOTES
SAP_USR = manager
SAP_USR_PW = 2023CC
SAP_DB_USR = sa
SAP_DB_PW = $Sap2020$
TIMEOUT = 0
IDCONFIGURACION = 1
#FIN

#CLC_FIS-PRD
SERVIDOR_BD_WMS = DESARROLLO8-PC\SQL2019
NOMBRE_BD_WMS = IMS4MB_CLC_FIS
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 2
TIMEOUT = 0
FORMATO_INGRESO_FISCAL =1
TIMEOUT_BD_ERP = 120
#FIN

#1-SERVER_PRODUCCION
SERVIDOR_BD_WMS = DESARROLLO8-PC\SQL2019
NOMBRE_BD_WMS = IMS4MB_CEALSA_QAP
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
IDCONFIGURACION = 1
SERVIDOR_SQL_ERP = 192.168.0.63
NOMBRE_BD_ERP = aritecdbpruebas
BD_ERP_USR = dts_userdb
BD_ERP_PWD = G9q&9Tf2
SEGURIDAD_INTEGRADA_ERP = NO
FORMATO_DESPACHO = 3
TIMEOUT_BD_ERP = 120
#FIN
