#CKFK-PRD
SERVIDOR_BD_WMS = DESKTOP-790O7S2\SQL2022
NOMBRE_BD_WMS = TOMWMS_KILLIOS_PRD
USUARIO_BD_WMS = sa
CLAVE_BD_WMS = sysadm
SEGURIDAD_INTEGRADA = NO
FORMATO_DESPACHO= 1
FORMATO_RECEPCION= 2
TIMEOUT = 0
FORMATO_DESPACHO= 2
IDCONFIGURACION = 3
FORMATO_RECEPCION=2
HANA_SL=https://10.238.151.130:50000/b1s/v1/
HANA_SL_USR=DevAccess
HANA_SL_PWD=d3V_205!W4
#FIN

