-- O1: Columnas del outbox i_nav_transacciones_out
-- Read-only. Devuelve: COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'i_nav_transacciones_out'
ORDER BY ORDINAL_POSITION;
