DEBUG = OFF

#QA
SERVIDOR = DESARROLLO7-PC\SQLEXPRESS
BD = IMS4MB_MOVESA
USUARIO = sa
CLAVE = sysadm
SEGURIDAD_INTEGRADA = NO
IPWCF=http://localhost:4180/
TIMEOUT = 0
#FIN

#DEV
SERVIDOR =192.168.125.28
BD = IMS4MB_DEV
USUARIO = mi3_user
CLAVE =mi3_user2018
SEGURIDAD_INTEGRADA = NO
IPWCF=http://localhost:4180/
TIMEOUT = 0
IDCONFIGURACION = -1
#FIN
